/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.stackone.stackone_client_java.models.components;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class ConditionType {

    /**
     * The type of the question's condition
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private JsonNullable<? extends QuestionParentQuestionValue> value;

    /**
     * The source value of the question's condition type
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("source_value")
    private JsonNullable<? extends QuestionParentQuestionSourceValue> sourceValue;

    @JsonCreator
    public ConditionType(
            @JsonProperty("value") JsonNullable<? extends QuestionParentQuestionValue> value,
            @JsonProperty("source_value") JsonNullable<? extends QuestionParentQuestionSourceValue> sourceValue) {
        Utils.checkNotNull(value, "value");
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.value = value;
        this.sourceValue = sourceValue;
    }
    
    public ConditionType() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * The type of the question's condition
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<QuestionParentQuestionValue> value() {
        return (JsonNullable<QuestionParentQuestionValue>) value;
    }

    /**
     * The source value of the question's condition type
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<QuestionParentQuestionSourceValue> sourceValue() {
        return (JsonNullable<QuestionParentQuestionSourceValue>) sourceValue;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The type of the question's condition
     */
    public ConditionType withValue(QuestionParentQuestionValue value) {
        Utils.checkNotNull(value, "value");
        this.value = JsonNullable.of(value);
        return this;
    }

    /**
     * The type of the question's condition
     */
    public ConditionType withValue(JsonNullable<? extends QuestionParentQuestionValue> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }

    /**
     * The source value of the question's condition type
     */
    public ConditionType withSourceValue(QuestionParentQuestionSourceValue sourceValue) {
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.sourceValue = JsonNullable.of(sourceValue);
        return this;
    }

    /**
     * The source value of the question's condition type
     */
    public ConditionType withSourceValue(JsonNullable<? extends QuestionParentQuestionSourceValue> sourceValue) {
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.sourceValue = sourceValue;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConditionType other = (ConditionType) o;
        return 
            Objects.deepEquals(this.value, other.value) &&
            Objects.deepEquals(this.sourceValue, other.sourceValue);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            value,
            sourceValue);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ConditionType.class,
                "value", value,
                "sourceValue", sourceValue);
    }
    
    public final static class Builder {
 
        private JsonNullable<? extends QuestionParentQuestionValue> value = JsonNullable.undefined();
 
        private JsonNullable<? extends QuestionParentQuestionSourceValue> sourceValue = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The type of the question's condition
         */
        public Builder value(QuestionParentQuestionValue value) {
            Utils.checkNotNull(value, "value");
            this.value = JsonNullable.of(value);
            return this;
        }

        /**
         * The type of the question's condition
         */
        public Builder value(JsonNullable<? extends QuestionParentQuestionValue> value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }

        /**
         * The source value of the question's condition type
         */
        public Builder sourceValue(QuestionParentQuestionSourceValue sourceValue) {
            Utils.checkNotNull(sourceValue, "sourceValue");
            this.sourceValue = JsonNullable.of(sourceValue);
            return this;
        }

        /**
         * The source value of the question's condition type
         */
        public Builder sourceValue(JsonNullable<? extends QuestionParentQuestionSourceValue> sourceValue) {
            Utils.checkNotNull(sourceValue, "sourceValue");
            this.sourceValue = sourceValue;
            return this;
        }
        
        public ConditionType build() {
            return new ConditionType(
                value,
                sourceValue);
        }
    }
}

