/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>Wrapper class for an "open" enum. "Open" enums are those that are expected
 * to evolve (particularly with the addition of enum members over time). If an
 * open enum is used then the appearance of unexpected enum values (say in a 
 * response from an updated an API) will not bring about a runtime error thus 
 * ensuring that non-updated client versions can continue to work without error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe
 * cache is maintained to ensure that). As a consequence instances created with the 
 * same value will satisfy reference equality (via {@code ==}).
 * 
 * <p>This class is intended to emulate an enum (in terms of common usage and with 
 * reference equality) but with the ability to carry unknown values. Unfortunately
 * Java does not permit the use of an instance in a switch expression but you can 
 * use the {@code asEnum()} method (after dealing with the `Optional` appropriately).
 *
 */
/**
 * ContentBlockStatusValue
 * 
 * <p>The Status of the content blocks.
 */
@JsonDeserialize(using = ContentBlockStatusValue._Deserializer.class)
@JsonSerialize(using = ContentBlockStatusValue._Serializer.class)
public class ContentBlockStatusValue {

    public static final ContentBlockStatusValue DRAFT = new ContentBlockStatusValue("draft");
    public static final ContentBlockStatusValue LIVE = new ContentBlockStatusValue("live");
    public static final ContentBlockStatusValue ARCHIVED = new ContentBlockStatusValue("archived");
    public static final ContentBlockStatusValue UNMAPPED_VALUE = new ContentBlockStatusValue("unmapped_value");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ContentBlockStatusValue> values = createValuesMap();
    private static final Map<String, ContentBlockStatusValueEnum> enums = createEnumsMap();

    private final String value;

    private ContentBlockStatusValue(String value) {
        this.value = value;
    }

    /**
     * Returns a ContentBlockStatusValue with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ContentBlockStatusValue
     */ 
    public static ContentBlockStatusValue of(String value) {
        synchronized (ContentBlockStatusValue.class) {
            return values.computeIfAbsent(value, v -> new ContentBlockStatusValue(v));
        }
    }

    public String value() {
        return value;
    }

    public Optional<ContentBlockStatusValueEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ContentBlockStatusValue other = (ContentBlockStatusValue) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ContentBlockStatusValue [value=" + value + "]";
    }

    // return an array just like an enum
    public static ContentBlockStatusValue[] values() {
        synchronized (ContentBlockStatusValue.class) {
            return values.values().toArray(new ContentBlockStatusValue[] {});
        }
    }

    private static final Map<String, ContentBlockStatusValue> createValuesMap() {
        Map<String, ContentBlockStatusValue> map = new LinkedHashMap<>();
        map.put("draft", DRAFT);
        map.put("live", LIVE);
        map.put("archived", ARCHIVED);
        map.put("unmapped_value", UNMAPPED_VALUE);
        return map;
    }

    private static final Map<String, ContentBlockStatusValueEnum> createEnumsMap() {
        Map<String, ContentBlockStatusValueEnum> map = new HashMap<>();
        map.put("draft", ContentBlockStatusValueEnum.DRAFT);
        map.put("live", ContentBlockStatusValueEnum.LIVE);
        map.put("archived", ContentBlockStatusValueEnum.ARCHIVED);
        map.put("unmapped_value", ContentBlockStatusValueEnum.UNMAPPED_VALUE);
        return map;
    }
    
    @SuppressWarnings("serial")
    public static final class _Serializer extends StdSerializer<ContentBlockStatusValue> {

        protected _Serializer() {
            super(ContentBlockStatusValue.class);
        }

        @Override
        public void serialize(ContentBlockStatusValue value, JsonGenerator g, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            g.writeObject(value.value);
        }
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends StdDeserializer<ContentBlockStatusValue> {

        protected _Deserializer() {
            super(ContentBlockStatusValue.class);
        }

        @Override
        public ContentBlockStatusValue deserialize(JsonParser p, DeserializationContext ctxt)
                throws IOException, JacksonException {
            String v = p.readValueAs(new TypeReference<String>() {});
            // use the factory method to ensure we get singletons
            return ContentBlockStatusValue.of(v);
        }
    }
    
    public enum ContentBlockStatusValueEnum {

        DRAFT("draft"),
        LIVE("live"),
        ARCHIVED("archived"),
        UNMAPPED_VALUE("unmapped_value"),;

        private final String value;

        private ContentBlockStatusValueEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

