/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.stackone.stackone_client_java.models.components;
import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


/**
 * <p>Wrapper class for an "open" enum. "Open" enums are those that are expected
 * to evolve (particularly with the addition of enum members over time). If an
 * open enum is used then the appearance of unexpected enum values (say in a 
 * response from an updated an API) will not bring about a runtime error thus 
 * ensuring that non-updated client versions can continue to work without error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe
 * cache is maintained to ensure that). As a consequence instances created with the 
 * same value will satisfy reference equality (via {@code ==}).
 * 
 * <p>This class is intended to emulate an enum (in terms of common usage and with 
 * reference equality) but with the ability to carry unknown values. Unfortunately
 * Java does not permit the use of an instance in a switch expression but you can 
 * use the {@code asEnum()} method (after dealing with the `Optional` appropriately).
 *
 */
/**
 * EmployeeNationalIdentityNumberCountryValue - The ISO3166-1 Alpha2 Code of the Country
 */
@JsonDeserialize(using = EmployeeNationalIdentityNumberCountryValue._Deserializer.class)
@JsonSerialize(using = EmployeeNationalIdentityNumberCountryValue._Serializer.class)
public class EmployeeNationalIdentityNumberCountryValue {

    public static final EmployeeNationalIdentityNumberCountryValue AF = new EmployeeNationalIdentityNumberCountryValue("AF");
    public static final EmployeeNationalIdentityNumberCountryValue AL = new EmployeeNationalIdentityNumberCountryValue("AL");
    public static final EmployeeNationalIdentityNumberCountryValue DZ = new EmployeeNationalIdentityNumberCountryValue("DZ");
    public static final EmployeeNationalIdentityNumberCountryValue AS = new EmployeeNationalIdentityNumberCountryValue("AS");
    public static final EmployeeNationalIdentityNumberCountryValue AD = new EmployeeNationalIdentityNumberCountryValue("AD");
    public static final EmployeeNationalIdentityNumberCountryValue AO = new EmployeeNationalIdentityNumberCountryValue("AO");
    public static final EmployeeNationalIdentityNumberCountryValue AI = new EmployeeNationalIdentityNumberCountryValue("AI");
    public static final EmployeeNationalIdentityNumberCountryValue AQ = new EmployeeNationalIdentityNumberCountryValue("AQ");
    public static final EmployeeNationalIdentityNumberCountryValue AG = new EmployeeNationalIdentityNumberCountryValue("AG");
    public static final EmployeeNationalIdentityNumberCountryValue AR = new EmployeeNationalIdentityNumberCountryValue("AR");
    public static final EmployeeNationalIdentityNumberCountryValue AM = new EmployeeNationalIdentityNumberCountryValue("AM");
    public static final EmployeeNationalIdentityNumberCountryValue AW = new EmployeeNationalIdentityNumberCountryValue("AW");
    public static final EmployeeNationalIdentityNumberCountryValue AU = new EmployeeNationalIdentityNumberCountryValue("AU");
    public static final EmployeeNationalIdentityNumberCountryValue AT = new EmployeeNationalIdentityNumberCountryValue("AT");
    public static final EmployeeNationalIdentityNumberCountryValue AZ = new EmployeeNationalIdentityNumberCountryValue("AZ");
    public static final EmployeeNationalIdentityNumberCountryValue BS = new EmployeeNationalIdentityNumberCountryValue("BS");
    public static final EmployeeNationalIdentityNumberCountryValue BH = new EmployeeNationalIdentityNumberCountryValue("BH");
    public static final EmployeeNationalIdentityNumberCountryValue BD = new EmployeeNationalIdentityNumberCountryValue("BD");
    public static final EmployeeNationalIdentityNumberCountryValue BB = new EmployeeNationalIdentityNumberCountryValue("BB");
    public static final EmployeeNationalIdentityNumberCountryValue BY = new EmployeeNationalIdentityNumberCountryValue("BY");
    public static final EmployeeNationalIdentityNumberCountryValue BE = new EmployeeNationalIdentityNumberCountryValue("BE");
    public static final EmployeeNationalIdentityNumberCountryValue BZ = new EmployeeNationalIdentityNumberCountryValue("BZ");
    public static final EmployeeNationalIdentityNumberCountryValue BJ = new EmployeeNationalIdentityNumberCountryValue("BJ");
    public static final EmployeeNationalIdentityNumberCountryValue BM = new EmployeeNationalIdentityNumberCountryValue("BM");
    public static final EmployeeNationalIdentityNumberCountryValue BT = new EmployeeNationalIdentityNumberCountryValue("BT");
    public static final EmployeeNationalIdentityNumberCountryValue BO = new EmployeeNationalIdentityNumberCountryValue("BO");
    public static final EmployeeNationalIdentityNumberCountryValue BQ = new EmployeeNationalIdentityNumberCountryValue("BQ");
    public static final EmployeeNationalIdentityNumberCountryValue BA = new EmployeeNationalIdentityNumberCountryValue("BA");
    public static final EmployeeNationalIdentityNumberCountryValue BW = new EmployeeNationalIdentityNumberCountryValue("BW");
    public static final EmployeeNationalIdentityNumberCountryValue BV = new EmployeeNationalIdentityNumberCountryValue("BV");
    public static final EmployeeNationalIdentityNumberCountryValue BR = new EmployeeNationalIdentityNumberCountryValue("BR");
    public static final EmployeeNationalIdentityNumberCountryValue IO = new EmployeeNationalIdentityNumberCountryValue("IO");
    public static final EmployeeNationalIdentityNumberCountryValue BN = new EmployeeNationalIdentityNumberCountryValue("BN");
    public static final EmployeeNationalIdentityNumberCountryValue BG = new EmployeeNationalIdentityNumberCountryValue("BG");
    public static final EmployeeNationalIdentityNumberCountryValue BF = new EmployeeNationalIdentityNumberCountryValue("BF");
    public static final EmployeeNationalIdentityNumberCountryValue BI = new EmployeeNationalIdentityNumberCountryValue("BI");
    public static final EmployeeNationalIdentityNumberCountryValue KH = new EmployeeNationalIdentityNumberCountryValue("KH");
    public static final EmployeeNationalIdentityNumberCountryValue CM = new EmployeeNationalIdentityNumberCountryValue("CM");
    public static final EmployeeNationalIdentityNumberCountryValue CA = new EmployeeNationalIdentityNumberCountryValue("CA");
    public static final EmployeeNationalIdentityNumberCountryValue CV = new EmployeeNationalIdentityNumberCountryValue("CV");
    public static final EmployeeNationalIdentityNumberCountryValue KY = new EmployeeNationalIdentityNumberCountryValue("KY");
    public static final EmployeeNationalIdentityNumberCountryValue CF = new EmployeeNationalIdentityNumberCountryValue("CF");
    public static final EmployeeNationalIdentityNumberCountryValue TD = new EmployeeNationalIdentityNumberCountryValue("TD");
    public static final EmployeeNationalIdentityNumberCountryValue CL = new EmployeeNationalIdentityNumberCountryValue("CL");
    public static final EmployeeNationalIdentityNumberCountryValue CN = new EmployeeNationalIdentityNumberCountryValue("CN");
    public static final EmployeeNationalIdentityNumberCountryValue CX = new EmployeeNationalIdentityNumberCountryValue("CX");
    public static final EmployeeNationalIdentityNumberCountryValue CC = new EmployeeNationalIdentityNumberCountryValue("CC");
    public static final EmployeeNationalIdentityNumberCountryValue CO = new EmployeeNationalIdentityNumberCountryValue("CO");
    public static final EmployeeNationalIdentityNumberCountryValue KM = new EmployeeNationalIdentityNumberCountryValue("KM");
    public static final EmployeeNationalIdentityNumberCountryValue CG = new EmployeeNationalIdentityNumberCountryValue("CG");
    public static final EmployeeNationalIdentityNumberCountryValue CD = new EmployeeNationalIdentityNumberCountryValue("CD");
    public static final EmployeeNationalIdentityNumberCountryValue CK = new EmployeeNationalIdentityNumberCountryValue("CK");
    public static final EmployeeNationalIdentityNumberCountryValue CR = new EmployeeNationalIdentityNumberCountryValue("CR");
    public static final EmployeeNationalIdentityNumberCountryValue HR = new EmployeeNationalIdentityNumberCountryValue("HR");
    public static final EmployeeNationalIdentityNumberCountryValue CU = new EmployeeNationalIdentityNumberCountryValue("CU");
    public static final EmployeeNationalIdentityNumberCountryValue CW = new EmployeeNationalIdentityNumberCountryValue("CW");
    public static final EmployeeNationalIdentityNumberCountryValue CY = new EmployeeNationalIdentityNumberCountryValue("CY");
    public static final EmployeeNationalIdentityNumberCountryValue CZ = new EmployeeNationalIdentityNumberCountryValue("CZ");
    public static final EmployeeNationalIdentityNumberCountryValue CI = new EmployeeNationalIdentityNumberCountryValue("CI");
    public static final EmployeeNationalIdentityNumberCountryValue DK = new EmployeeNationalIdentityNumberCountryValue("DK");
    public static final EmployeeNationalIdentityNumberCountryValue DJ = new EmployeeNationalIdentityNumberCountryValue("DJ");
    public static final EmployeeNationalIdentityNumberCountryValue DM = new EmployeeNationalIdentityNumberCountryValue("DM");
    public static final EmployeeNationalIdentityNumberCountryValue DO = new EmployeeNationalIdentityNumberCountryValue("DO");
    public static final EmployeeNationalIdentityNumberCountryValue EC = new EmployeeNationalIdentityNumberCountryValue("EC");
    public static final EmployeeNationalIdentityNumberCountryValue EG = new EmployeeNationalIdentityNumberCountryValue("EG");
    public static final EmployeeNationalIdentityNumberCountryValue SV = new EmployeeNationalIdentityNumberCountryValue("SV");
    public static final EmployeeNationalIdentityNumberCountryValue GQ = new EmployeeNationalIdentityNumberCountryValue("GQ");
    public static final EmployeeNationalIdentityNumberCountryValue ER = new EmployeeNationalIdentityNumberCountryValue("ER");
    public static final EmployeeNationalIdentityNumberCountryValue EE = new EmployeeNationalIdentityNumberCountryValue("EE");
    public static final EmployeeNationalIdentityNumberCountryValue ET = new EmployeeNationalIdentityNumberCountryValue("ET");
    public static final EmployeeNationalIdentityNumberCountryValue FK = new EmployeeNationalIdentityNumberCountryValue("FK");
    public static final EmployeeNationalIdentityNumberCountryValue FO = new EmployeeNationalIdentityNumberCountryValue("FO");
    public static final EmployeeNationalIdentityNumberCountryValue FJ = new EmployeeNationalIdentityNumberCountryValue("FJ");
    public static final EmployeeNationalIdentityNumberCountryValue FI = new EmployeeNationalIdentityNumberCountryValue("FI");
    public static final EmployeeNationalIdentityNumberCountryValue FR = new EmployeeNationalIdentityNumberCountryValue("FR");
    public static final EmployeeNationalIdentityNumberCountryValue GF = new EmployeeNationalIdentityNumberCountryValue("GF");
    public static final EmployeeNationalIdentityNumberCountryValue PF = new EmployeeNationalIdentityNumberCountryValue("PF");
    public static final EmployeeNationalIdentityNumberCountryValue TF = new EmployeeNationalIdentityNumberCountryValue("TF");
    public static final EmployeeNationalIdentityNumberCountryValue GA = new EmployeeNationalIdentityNumberCountryValue("GA");
    public static final EmployeeNationalIdentityNumberCountryValue GM = new EmployeeNationalIdentityNumberCountryValue("GM");
    public static final EmployeeNationalIdentityNumberCountryValue GE = new EmployeeNationalIdentityNumberCountryValue("GE");
    public static final EmployeeNationalIdentityNumberCountryValue DE = new EmployeeNationalIdentityNumberCountryValue("DE");
    public static final EmployeeNationalIdentityNumberCountryValue GH = new EmployeeNationalIdentityNumberCountryValue("GH");
    public static final EmployeeNationalIdentityNumberCountryValue GI = new EmployeeNationalIdentityNumberCountryValue("GI");
    public static final EmployeeNationalIdentityNumberCountryValue GR = new EmployeeNationalIdentityNumberCountryValue("GR");
    public static final EmployeeNationalIdentityNumberCountryValue GL = new EmployeeNationalIdentityNumberCountryValue("GL");
    public static final EmployeeNationalIdentityNumberCountryValue GD = new EmployeeNationalIdentityNumberCountryValue("GD");
    public static final EmployeeNationalIdentityNumberCountryValue GP = new EmployeeNationalIdentityNumberCountryValue("GP");
    public static final EmployeeNationalIdentityNumberCountryValue GU = new EmployeeNationalIdentityNumberCountryValue("GU");
    public static final EmployeeNationalIdentityNumberCountryValue GT = new EmployeeNationalIdentityNumberCountryValue("GT");
    public static final EmployeeNationalIdentityNumberCountryValue GG = new EmployeeNationalIdentityNumberCountryValue("GG");
    public static final EmployeeNationalIdentityNumberCountryValue GN = new EmployeeNationalIdentityNumberCountryValue("GN");
    public static final EmployeeNationalIdentityNumberCountryValue GW = new EmployeeNationalIdentityNumberCountryValue("GW");
    public static final EmployeeNationalIdentityNumberCountryValue GY = new EmployeeNationalIdentityNumberCountryValue("GY");
    public static final EmployeeNationalIdentityNumberCountryValue HT = new EmployeeNationalIdentityNumberCountryValue("HT");
    public static final EmployeeNationalIdentityNumberCountryValue HM = new EmployeeNationalIdentityNumberCountryValue("HM");
    public static final EmployeeNationalIdentityNumberCountryValue VA = new EmployeeNationalIdentityNumberCountryValue("VA");
    public static final EmployeeNationalIdentityNumberCountryValue HN = new EmployeeNationalIdentityNumberCountryValue("HN");
    public static final EmployeeNationalIdentityNumberCountryValue HK = new EmployeeNationalIdentityNumberCountryValue("HK");
    public static final EmployeeNationalIdentityNumberCountryValue HU = new EmployeeNationalIdentityNumberCountryValue("HU");
    public static final EmployeeNationalIdentityNumberCountryValue IS = new EmployeeNationalIdentityNumberCountryValue("IS");
    public static final EmployeeNationalIdentityNumberCountryValue IN = new EmployeeNationalIdentityNumberCountryValue("IN");
    public static final EmployeeNationalIdentityNumberCountryValue ID = new EmployeeNationalIdentityNumberCountryValue("ID");
    public static final EmployeeNationalIdentityNumberCountryValue IR = new EmployeeNationalIdentityNumberCountryValue("IR");
    public static final EmployeeNationalIdentityNumberCountryValue IQ = new EmployeeNationalIdentityNumberCountryValue("IQ");
    public static final EmployeeNationalIdentityNumberCountryValue IE = new EmployeeNationalIdentityNumberCountryValue("IE");
    public static final EmployeeNationalIdentityNumberCountryValue IM = new EmployeeNationalIdentityNumberCountryValue("IM");
    public static final EmployeeNationalIdentityNumberCountryValue IL = new EmployeeNationalIdentityNumberCountryValue("IL");
    public static final EmployeeNationalIdentityNumberCountryValue IT = new EmployeeNationalIdentityNumberCountryValue("IT");
    public static final EmployeeNationalIdentityNumberCountryValue JM = new EmployeeNationalIdentityNumberCountryValue("JM");
    public static final EmployeeNationalIdentityNumberCountryValue JP = new EmployeeNationalIdentityNumberCountryValue("JP");
    public static final EmployeeNationalIdentityNumberCountryValue JE = new EmployeeNationalIdentityNumberCountryValue("JE");
    public static final EmployeeNationalIdentityNumberCountryValue JO = new EmployeeNationalIdentityNumberCountryValue("JO");
    public static final EmployeeNationalIdentityNumberCountryValue KZ = new EmployeeNationalIdentityNumberCountryValue("KZ");
    public static final EmployeeNationalIdentityNumberCountryValue KE = new EmployeeNationalIdentityNumberCountryValue("KE");
    public static final EmployeeNationalIdentityNumberCountryValue KI = new EmployeeNationalIdentityNumberCountryValue("KI");
    public static final EmployeeNationalIdentityNumberCountryValue KP = new EmployeeNationalIdentityNumberCountryValue("KP");
    public static final EmployeeNationalIdentityNumberCountryValue KR = new EmployeeNationalIdentityNumberCountryValue("KR");
    public static final EmployeeNationalIdentityNumberCountryValue KW = new EmployeeNationalIdentityNumberCountryValue("KW");
    public static final EmployeeNationalIdentityNumberCountryValue KG = new EmployeeNationalIdentityNumberCountryValue("KG");
    public static final EmployeeNationalIdentityNumberCountryValue LA = new EmployeeNationalIdentityNumberCountryValue("LA");
    public static final EmployeeNationalIdentityNumberCountryValue LV = new EmployeeNationalIdentityNumberCountryValue("LV");
    public static final EmployeeNationalIdentityNumberCountryValue LB = new EmployeeNationalIdentityNumberCountryValue("LB");
    public static final EmployeeNationalIdentityNumberCountryValue LS = new EmployeeNationalIdentityNumberCountryValue("LS");
    public static final EmployeeNationalIdentityNumberCountryValue LR = new EmployeeNationalIdentityNumberCountryValue("LR");
    public static final EmployeeNationalIdentityNumberCountryValue LY = new EmployeeNationalIdentityNumberCountryValue("LY");
    public static final EmployeeNationalIdentityNumberCountryValue LI = new EmployeeNationalIdentityNumberCountryValue("LI");
    public static final EmployeeNationalIdentityNumberCountryValue LT = new EmployeeNationalIdentityNumberCountryValue("LT");
    public static final EmployeeNationalIdentityNumberCountryValue LU = new EmployeeNationalIdentityNumberCountryValue("LU");
    public static final EmployeeNationalIdentityNumberCountryValue MO = new EmployeeNationalIdentityNumberCountryValue("MO");
    public static final EmployeeNationalIdentityNumberCountryValue MK = new EmployeeNationalIdentityNumberCountryValue("MK");
    public static final EmployeeNationalIdentityNumberCountryValue MG = new EmployeeNationalIdentityNumberCountryValue("MG");
    public static final EmployeeNationalIdentityNumberCountryValue MW = new EmployeeNationalIdentityNumberCountryValue("MW");
    public static final EmployeeNationalIdentityNumberCountryValue MY = new EmployeeNationalIdentityNumberCountryValue("MY");
    public static final EmployeeNationalIdentityNumberCountryValue MV = new EmployeeNationalIdentityNumberCountryValue("MV");
    public static final EmployeeNationalIdentityNumberCountryValue ML = new EmployeeNationalIdentityNumberCountryValue("ML");
    public static final EmployeeNationalIdentityNumberCountryValue MT = new EmployeeNationalIdentityNumberCountryValue("MT");
    public static final EmployeeNationalIdentityNumberCountryValue MH = new EmployeeNationalIdentityNumberCountryValue("MH");
    public static final EmployeeNationalIdentityNumberCountryValue MQ = new EmployeeNationalIdentityNumberCountryValue("MQ");
    public static final EmployeeNationalIdentityNumberCountryValue MR = new EmployeeNationalIdentityNumberCountryValue("MR");
    public static final EmployeeNationalIdentityNumberCountryValue MU = new EmployeeNationalIdentityNumberCountryValue("MU");
    public static final EmployeeNationalIdentityNumberCountryValue YT = new EmployeeNationalIdentityNumberCountryValue("YT");
    public static final EmployeeNationalIdentityNumberCountryValue MX = new EmployeeNationalIdentityNumberCountryValue("MX");
    public static final EmployeeNationalIdentityNumberCountryValue FM = new EmployeeNationalIdentityNumberCountryValue("FM");
    public static final EmployeeNationalIdentityNumberCountryValue MD = new EmployeeNationalIdentityNumberCountryValue("MD");
    public static final EmployeeNationalIdentityNumberCountryValue MC = new EmployeeNationalIdentityNumberCountryValue("MC");
    public static final EmployeeNationalIdentityNumberCountryValue MN = new EmployeeNationalIdentityNumberCountryValue("MN");
    public static final EmployeeNationalIdentityNumberCountryValue ME = new EmployeeNationalIdentityNumberCountryValue("ME");
    public static final EmployeeNationalIdentityNumberCountryValue MS = new EmployeeNationalIdentityNumberCountryValue("MS");
    public static final EmployeeNationalIdentityNumberCountryValue MA = new EmployeeNationalIdentityNumberCountryValue("MA");
    public static final EmployeeNationalIdentityNumberCountryValue MZ = new EmployeeNationalIdentityNumberCountryValue("MZ");
    public static final EmployeeNationalIdentityNumberCountryValue MM = new EmployeeNationalIdentityNumberCountryValue("MM");
    public static final EmployeeNationalIdentityNumberCountryValue NA = new EmployeeNationalIdentityNumberCountryValue("NA");
    public static final EmployeeNationalIdentityNumberCountryValue NR = new EmployeeNationalIdentityNumberCountryValue("NR");
    public static final EmployeeNationalIdentityNumberCountryValue NP = new EmployeeNationalIdentityNumberCountryValue("NP");
    public static final EmployeeNationalIdentityNumberCountryValue NL = new EmployeeNationalIdentityNumberCountryValue("NL");
    public static final EmployeeNationalIdentityNumberCountryValue NC = new EmployeeNationalIdentityNumberCountryValue("NC");
    public static final EmployeeNationalIdentityNumberCountryValue NZ = new EmployeeNationalIdentityNumberCountryValue("NZ");
    public static final EmployeeNationalIdentityNumberCountryValue NI = new EmployeeNationalIdentityNumberCountryValue("NI");
    public static final EmployeeNationalIdentityNumberCountryValue NE = new EmployeeNationalIdentityNumberCountryValue("NE");
    public static final EmployeeNationalIdentityNumberCountryValue NG = new EmployeeNationalIdentityNumberCountryValue("NG");
    public static final EmployeeNationalIdentityNumberCountryValue NU = new EmployeeNationalIdentityNumberCountryValue("NU");
    public static final EmployeeNationalIdentityNumberCountryValue NF = new EmployeeNationalIdentityNumberCountryValue("NF");
    public static final EmployeeNationalIdentityNumberCountryValue MP = new EmployeeNationalIdentityNumberCountryValue("MP");
    public static final EmployeeNationalIdentityNumberCountryValue NO = new EmployeeNationalIdentityNumberCountryValue("NO");
    public static final EmployeeNationalIdentityNumberCountryValue OM = new EmployeeNationalIdentityNumberCountryValue("OM");
    public static final EmployeeNationalIdentityNumberCountryValue PK = new EmployeeNationalIdentityNumberCountryValue("PK");
    public static final EmployeeNationalIdentityNumberCountryValue PW = new EmployeeNationalIdentityNumberCountryValue("PW");
    public static final EmployeeNationalIdentityNumberCountryValue PS = new EmployeeNationalIdentityNumberCountryValue("PS");
    public static final EmployeeNationalIdentityNumberCountryValue PA = new EmployeeNationalIdentityNumberCountryValue("PA");
    public static final EmployeeNationalIdentityNumberCountryValue PG = new EmployeeNationalIdentityNumberCountryValue("PG");
    public static final EmployeeNationalIdentityNumberCountryValue PY = new EmployeeNationalIdentityNumberCountryValue("PY");
    public static final EmployeeNationalIdentityNumberCountryValue PE = new EmployeeNationalIdentityNumberCountryValue("PE");
    public static final EmployeeNationalIdentityNumberCountryValue PH = new EmployeeNationalIdentityNumberCountryValue("PH");
    public static final EmployeeNationalIdentityNumberCountryValue PN = new EmployeeNationalIdentityNumberCountryValue("PN");
    public static final EmployeeNationalIdentityNumberCountryValue PL = new EmployeeNationalIdentityNumberCountryValue("PL");
    public static final EmployeeNationalIdentityNumberCountryValue PT = new EmployeeNationalIdentityNumberCountryValue("PT");
    public static final EmployeeNationalIdentityNumberCountryValue PR = new EmployeeNationalIdentityNumberCountryValue("PR");
    public static final EmployeeNationalIdentityNumberCountryValue QA = new EmployeeNationalIdentityNumberCountryValue("QA");
    public static final EmployeeNationalIdentityNumberCountryValue RO = new EmployeeNationalIdentityNumberCountryValue("RO");
    public static final EmployeeNationalIdentityNumberCountryValue RU = new EmployeeNationalIdentityNumberCountryValue("RU");
    public static final EmployeeNationalIdentityNumberCountryValue RW = new EmployeeNationalIdentityNumberCountryValue("RW");
    public static final EmployeeNationalIdentityNumberCountryValue RE = new EmployeeNationalIdentityNumberCountryValue("RE");
    public static final EmployeeNationalIdentityNumberCountryValue BL = new EmployeeNationalIdentityNumberCountryValue("BL");
    public static final EmployeeNationalIdentityNumberCountryValue SH = new EmployeeNationalIdentityNumberCountryValue("SH");
    public static final EmployeeNationalIdentityNumberCountryValue KN = new EmployeeNationalIdentityNumberCountryValue("KN");
    public static final EmployeeNationalIdentityNumberCountryValue LC = new EmployeeNationalIdentityNumberCountryValue("LC");
    public static final EmployeeNationalIdentityNumberCountryValue MF = new EmployeeNationalIdentityNumberCountryValue("MF");
    public static final EmployeeNationalIdentityNumberCountryValue PM = new EmployeeNationalIdentityNumberCountryValue("PM");
    public static final EmployeeNationalIdentityNumberCountryValue VC = new EmployeeNationalIdentityNumberCountryValue("VC");
    public static final EmployeeNationalIdentityNumberCountryValue WS = new EmployeeNationalIdentityNumberCountryValue("WS");
    public static final EmployeeNationalIdentityNumberCountryValue SM = new EmployeeNationalIdentityNumberCountryValue("SM");
    public static final EmployeeNationalIdentityNumberCountryValue ST = new EmployeeNationalIdentityNumberCountryValue("ST");
    public static final EmployeeNationalIdentityNumberCountryValue SA = new EmployeeNationalIdentityNumberCountryValue("SA");
    public static final EmployeeNationalIdentityNumberCountryValue SN = new EmployeeNationalIdentityNumberCountryValue("SN");
    public static final EmployeeNationalIdentityNumberCountryValue RS = new EmployeeNationalIdentityNumberCountryValue("RS");
    public static final EmployeeNationalIdentityNumberCountryValue SC = new EmployeeNationalIdentityNumberCountryValue("SC");
    public static final EmployeeNationalIdentityNumberCountryValue SL = new EmployeeNationalIdentityNumberCountryValue("SL");
    public static final EmployeeNationalIdentityNumberCountryValue SG = new EmployeeNationalIdentityNumberCountryValue("SG");
    public static final EmployeeNationalIdentityNumberCountryValue SX = new EmployeeNationalIdentityNumberCountryValue("SX");
    public static final EmployeeNationalIdentityNumberCountryValue SK = new EmployeeNationalIdentityNumberCountryValue("SK");
    public static final EmployeeNationalIdentityNumberCountryValue SI = new EmployeeNationalIdentityNumberCountryValue("SI");
    public static final EmployeeNationalIdentityNumberCountryValue SB = new EmployeeNationalIdentityNumberCountryValue("SB");
    public static final EmployeeNationalIdentityNumberCountryValue SO = new EmployeeNationalIdentityNumberCountryValue("SO");
    public static final EmployeeNationalIdentityNumberCountryValue ZA = new EmployeeNationalIdentityNumberCountryValue("ZA");
    public static final EmployeeNationalIdentityNumberCountryValue GS = new EmployeeNationalIdentityNumberCountryValue("GS");
    public static final EmployeeNationalIdentityNumberCountryValue SS = new EmployeeNationalIdentityNumberCountryValue("SS");
    public static final EmployeeNationalIdentityNumberCountryValue ES = new EmployeeNationalIdentityNumberCountryValue("ES");
    public static final EmployeeNationalIdentityNumberCountryValue LK = new EmployeeNationalIdentityNumberCountryValue("LK");
    public static final EmployeeNationalIdentityNumberCountryValue SD = new EmployeeNationalIdentityNumberCountryValue("SD");
    public static final EmployeeNationalIdentityNumberCountryValue SR = new EmployeeNationalIdentityNumberCountryValue("SR");
    public static final EmployeeNationalIdentityNumberCountryValue SJ = new EmployeeNationalIdentityNumberCountryValue("SJ");
    public static final EmployeeNationalIdentityNumberCountryValue SZ = new EmployeeNationalIdentityNumberCountryValue("SZ");
    public static final EmployeeNationalIdentityNumberCountryValue SE = new EmployeeNationalIdentityNumberCountryValue("SE");
    public static final EmployeeNationalIdentityNumberCountryValue CH = new EmployeeNationalIdentityNumberCountryValue("CH");
    public static final EmployeeNationalIdentityNumberCountryValue SY = new EmployeeNationalIdentityNumberCountryValue("SY");
    public static final EmployeeNationalIdentityNumberCountryValue TW = new EmployeeNationalIdentityNumberCountryValue("TW");
    public static final EmployeeNationalIdentityNumberCountryValue TJ = new EmployeeNationalIdentityNumberCountryValue("TJ");
    public static final EmployeeNationalIdentityNumberCountryValue TZ = new EmployeeNationalIdentityNumberCountryValue("TZ");
    public static final EmployeeNationalIdentityNumberCountryValue TH = new EmployeeNationalIdentityNumberCountryValue("TH");
    public static final EmployeeNationalIdentityNumberCountryValue TL = new EmployeeNationalIdentityNumberCountryValue("TL");
    public static final EmployeeNationalIdentityNumberCountryValue TG = new EmployeeNationalIdentityNumberCountryValue("TG");
    public static final EmployeeNationalIdentityNumberCountryValue TK = new EmployeeNationalIdentityNumberCountryValue("TK");
    public static final EmployeeNationalIdentityNumberCountryValue TO = new EmployeeNationalIdentityNumberCountryValue("TO");
    public static final EmployeeNationalIdentityNumberCountryValue TT = new EmployeeNationalIdentityNumberCountryValue("TT");
    public static final EmployeeNationalIdentityNumberCountryValue TN = new EmployeeNationalIdentityNumberCountryValue("TN");
    public static final EmployeeNationalIdentityNumberCountryValue TR = new EmployeeNationalIdentityNumberCountryValue("TR");
    public static final EmployeeNationalIdentityNumberCountryValue TM = new EmployeeNationalIdentityNumberCountryValue("TM");
    public static final EmployeeNationalIdentityNumberCountryValue TC = new EmployeeNationalIdentityNumberCountryValue("TC");
    public static final EmployeeNationalIdentityNumberCountryValue TV = new EmployeeNationalIdentityNumberCountryValue("TV");
    public static final EmployeeNationalIdentityNumberCountryValue UG = new EmployeeNationalIdentityNumberCountryValue("UG");
    public static final EmployeeNationalIdentityNumberCountryValue UA = new EmployeeNationalIdentityNumberCountryValue("UA");
    public static final EmployeeNationalIdentityNumberCountryValue AE = new EmployeeNationalIdentityNumberCountryValue("AE");
    public static final EmployeeNationalIdentityNumberCountryValue GB = new EmployeeNationalIdentityNumberCountryValue("GB");
    public static final EmployeeNationalIdentityNumberCountryValue US = new EmployeeNationalIdentityNumberCountryValue("US");
    public static final EmployeeNationalIdentityNumberCountryValue UM = new EmployeeNationalIdentityNumberCountryValue("UM");
    public static final EmployeeNationalIdentityNumberCountryValue UY = new EmployeeNationalIdentityNumberCountryValue("UY");
    public static final EmployeeNationalIdentityNumberCountryValue UZ = new EmployeeNationalIdentityNumberCountryValue("UZ");
    public static final EmployeeNationalIdentityNumberCountryValue VU = new EmployeeNationalIdentityNumberCountryValue("VU");
    public static final EmployeeNationalIdentityNumberCountryValue VE = new EmployeeNationalIdentityNumberCountryValue("VE");
    public static final EmployeeNationalIdentityNumberCountryValue VN = new EmployeeNationalIdentityNumberCountryValue("VN");
    public static final EmployeeNationalIdentityNumberCountryValue VG = new EmployeeNationalIdentityNumberCountryValue("VG");
    public static final EmployeeNationalIdentityNumberCountryValue VI = new EmployeeNationalIdentityNumberCountryValue("VI");
    public static final EmployeeNationalIdentityNumberCountryValue WF = new EmployeeNationalIdentityNumberCountryValue("WF");
    public static final EmployeeNationalIdentityNumberCountryValue EH = new EmployeeNationalIdentityNumberCountryValue("EH");
    public static final EmployeeNationalIdentityNumberCountryValue YE = new EmployeeNationalIdentityNumberCountryValue("YE");
    public static final EmployeeNationalIdentityNumberCountryValue ZM = new EmployeeNationalIdentityNumberCountryValue("ZM");
    public static final EmployeeNationalIdentityNumberCountryValue ZW = new EmployeeNationalIdentityNumberCountryValue("ZW");
    public static final EmployeeNationalIdentityNumberCountryValue UNMAPPED_VALUE = new EmployeeNationalIdentityNumberCountryValue("unmapped_value");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EmployeeNationalIdentityNumberCountryValue> values = createValuesMap();
    private static final Map<String, EmployeeNationalIdentityNumberCountryValueEnum> enums = createEnumsMap();

    private final String value;

    private EmployeeNationalIdentityNumberCountryValue(String value) {
        this.value = value;
    }

    /**
     * Returns a EmployeeNationalIdentityNumberCountryValue with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EmployeeNationalIdentityNumberCountryValue
     */ 
    public static EmployeeNationalIdentityNumberCountryValue of(String value) {
        synchronized (EmployeeNationalIdentityNumberCountryValue.class) {
            return values.computeIfAbsent(value, v -> new EmployeeNationalIdentityNumberCountryValue(v));
        }
    }

    public String value() {
        return value;
    }

    public Optional<EmployeeNationalIdentityNumberCountryValueEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EmployeeNationalIdentityNumberCountryValue other = (EmployeeNationalIdentityNumberCountryValue) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EmployeeNationalIdentityNumberCountryValue [value=" + value + "]";
    }

    // return an array just like an enum
    public static EmployeeNationalIdentityNumberCountryValue[] values() {
        synchronized (EmployeeNationalIdentityNumberCountryValue.class) {
            return values.values().toArray(new EmployeeNationalIdentityNumberCountryValue[] {});
        }
    }

    private static final Map<String, EmployeeNationalIdentityNumberCountryValue> createValuesMap() {
        Map<String, EmployeeNationalIdentityNumberCountryValue> map = new LinkedHashMap<>();
        map.put("AF", AF);
        map.put("AL", AL);
        map.put("DZ", DZ);
        map.put("AS", AS);
        map.put("AD", AD);
        map.put("AO", AO);
        map.put("AI", AI);
        map.put("AQ", AQ);
        map.put("AG", AG);
        map.put("AR", AR);
        map.put("AM", AM);
        map.put("AW", AW);
        map.put("AU", AU);
        map.put("AT", AT);
        map.put("AZ", AZ);
        map.put("BS", BS);
        map.put("BH", BH);
        map.put("BD", BD);
        map.put("BB", BB);
        map.put("BY", BY);
        map.put("BE", BE);
        map.put("BZ", BZ);
        map.put("BJ", BJ);
        map.put("BM", BM);
        map.put("BT", BT);
        map.put("BO", BO);
        map.put("BQ", BQ);
        map.put("BA", BA);
        map.put("BW", BW);
        map.put("BV", BV);
        map.put("BR", BR);
        map.put("IO", IO);
        map.put("BN", BN);
        map.put("BG", BG);
        map.put("BF", BF);
        map.put("BI", BI);
        map.put("KH", KH);
        map.put("CM", CM);
        map.put("CA", CA);
        map.put("CV", CV);
        map.put("KY", KY);
        map.put("CF", CF);
        map.put("TD", TD);
        map.put("CL", CL);
        map.put("CN", CN);
        map.put("CX", CX);
        map.put("CC", CC);
        map.put("CO", CO);
        map.put("KM", KM);
        map.put("CG", CG);
        map.put("CD", CD);
        map.put("CK", CK);
        map.put("CR", CR);
        map.put("HR", HR);
        map.put("CU", CU);
        map.put("CW", CW);
        map.put("CY", CY);
        map.put("CZ", CZ);
        map.put("CI", CI);
        map.put("DK", DK);
        map.put("DJ", DJ);
        map.put("DM", DM);
        map.put("DO", DO);
        map.put("EC", EC);
        map.put("EG", EG);
        map.put("SV", SV);
        map.put("GQ", GQ);
        map.put("ER", ER);
        map.put("EE", EE);
        map.put("ET", ET);
        map.put("FK", FK);
        map.put("FO", FO);
        map.put("FJ", FJ);
        map.put("FI", FI);
        map.put("FR", FR);
        map.put("GF", GF);
        map.put("PF", PF);
        map.put("TF", TF);
        map.put("GA", GA);
        map.put("GM", GM);
        map.put("GE", GE);
        map.put("DE", DE);
        map.put("GH", GH);
        map.put("GI", GI);
        map.put("GR", GR);
        map.put("GL", GL);
        map.put("GD", GD);
        map.put("GP", GP);
        map.put("GU", GU);
        map.put("GT", GT);
        map.put("GG", GG);
        map.put("GN", GN);
        map.put("GW", GW);
        map.put("GY", GY);
        map.put("HT", HT);
        map.put("HM", HM);
        map.put("VA", VA);
        map.put("HN", HN);
        map.put("HK", HK);
        map.put("HU", HU);
        map.put("IS", IS);
        map.put("IN", IN);
        map.put("ID", ID);
        map.put("IR", IR);
        map.put("IQ", IQ);
        map.put("IE", IE);
        map.put("IM", IM);
        map.put("IL", IL);
        map.put("IT", IT);
        map.put("JM", JM);
        map.put("JP", JP);
        map.put("JE", JE);
        map.put("JO", JO);
        map.put("KZ", KZ);
        map.put("KE", KE);
        map.put("KI", KI);
        map.put("KP", KP);
        map.put("KR", KR);
        map.put("KW", KW);
        map.put("KG", KG);
        map.put("LA", LA);
        map.put("LV", LV);
        map.put("LB", LB);
        map.put("LS", LS);
        map.put("LR", LR);
        map.put("LY", LY);
        map.put("LI", LI);
        map.put("LT", LT);
        map.put("LU", LU);
        map.put("MO", MO);
        map.put("MK", MK);
        map.put("MG", MG);
        map.put("MW", MW);
        map.put("MY", MY);
        map.put("MV", MV);
        map.put("ML", ML);
        map.put("MT", MT);
        map.put("MH", MH);
        map.put("MQ", MQ);
        map.put("MR", MR);
        map.put("MU", MU);
        map.put("YT", YT);
        map.put("MX", MX);
        map.put("FM", FM);
        map.put("MD", MD);
        map.put("MC", MC);
        map.put("MN", MN);
        map.put("ME", ME);
        map.put("MS", MS);
        map.put("MA", MA);
        map.put("MZ", MZ);
        map.put("MM", MM);
        map.put("NA", NA);
        map.put("NR", NR);
        map.put("NP", NP);
        map.put("NL", NL);
        map.put("NC", NC);
        map.put("NZ", NZ);
        map.put("NI", NI);
        map.put("NE", NE);
        map.put("NG", NG);
        map.put("NU", NU);
        map.put("NF", NF);
        map.put("MP", MP);
        map.put("NO", NO);
        map.put("OM", OM);
        map.put("PK", PK);
        map.put("PW", PW);
        map.put("PS", PS);
        map.put("PA", PA);
        map.put("PG", PG);
        map.put("PY", PY);
        map.put("PE", PE);
        map.put("PH", PH);
        map.put("PN", PN);
        map.put("PL", PL);
        map.put("PT", PT);
        map.put("PR", PR);
        map.put("QA", QA);
        map.put("RO", RO);
        map.put("RU", RU);
        map.put("RW", RW);
        map.put("RE", RE);
        map.put("BL", BL);
        map.put("SH", SH);
        map.put("KN", KN);
        map.put("LC", LC);
        map.put("MF", MF);
        map.put("PM", PM);
        map.put("VC", VC);
        map.put("WS", WS);
        map.put("SM", SM);
        map.put("ST", ST);
        map.put("SA", SA);
        map.put("SN", SN);
        map.put("RS", RS);
        map.put("SC", SC);
        map.put("SL", SL);
        map.put("SG", SG);
        map.put("SX", SX);
        map.put("SK", SK);
        map.put("SI", SI);
        map.put("SB", SB);
        map.put("SO", SO);
        map.put("ZA", ZA);
        map.put("GS", GS);
        map.put("SS", SS);
        map.put("ES", ES);
        map.put("LK", LK);
        map.put("SD", SD);
        map.put("SR", SR);
        map.put("SJ", SJ);
        map.put("SZ", SZ);
        map.put("SE", SE);
        map.put("CH", CH);
        map.put("SY", SY);
        map.put("TW", TW);
        map.put("TJ", TJ);
        map.put("TZ", TZ);
        map.put("TH", TH);
        map.put("TL", TL);
        map.put("TG", TG);
        map.put("TK", TK);
        map.put("TO", TO);
        map.put("TT", TT);
        map.put("TN", TN);
        map.put("TR", TR);
        map.put("TM", TM);
        map.put("TC", TC);
        map.put("TV", TV);
        map.put("UG", UG);
        map.put("UA", UA);
        map.put("AE", AE);
        map.put("GB", GB);
        map.put("US", US);
        map.put("UM", UM);
        map.put("UY", UY);
        map.put("UZ", UZ);
        map.put("VU", VU);
        map.put("VE", VE);
        map.put("VN", VN);
        map.put("VG", VG);
        map.put("VI", VI);
        map.put("WF", WF);
        map.put("EH", EH);
        map.put("YE", YE);
        map.put("ZM", ZM);
        map.put("ZW", ZW);
        map.put("unmapped_value", UNMAPPED_VALUE);
        return map;
    }

    private static final Map<String, EmployeeNationalIdentityNumberCountryValueEnum> createEnumsMap() {
        Map<String, EmployeeNationalIdentityNumberCountryValueEnum> map = new HashMap<>();
        map.put("AF", EmployeeNationalIdentityNumberCountryValueEnum.AF);
        map.put("AL", EmployeeNationalIdentityNumberCountryValueEnum.AL);
        map.put("DZ", EmployeeNationalIdentityNumberCountryValueEnum.DZ);
        map.put("AS", EmployeeNationalIdentityNumberCountryValueEnum.AS);
        map.put("AD", EmployeeNationalIdentityNumberCountryValueEnum.AD);
        map.put("AO", EmployeeNationalIdentityNumberCountryValueEnum.AO);
        map.put("AI", EmployeeNationalIdentityNumberCountryValueEnum.AI);
        map.put("AQ", EmployeeNationalIdentityNumberCountryValueEnum.AQ);
        map.put("AG", EmployeeNationalIdentityNumberCountryValueEnum.AG);
        map.put("AR", EmployeeNationalIdentityNumberCountryValueEnum.AR);
        map.put("AM", EmployeeNationalIdentityNumberCountryValueEnum.AM);
        map.put("AW", EmployeeNationalIdentityNumberCountryValueEnum.AW);
        map.put("AU", EmployeeNationalIdentityNumberCountryValueEnum.AU);
        map.put("AT", EmployeeNationalIdentityNumberCountryValueEnum.AT);
        map.put("AZ", EmployeeNationalIdentityNumberCountryValueEnum.AZ);
        map.put("BS", EmployeeNationalIdentityNumberCountryValueEnum.BS);
        map.put("BH", EmployeeNationalIdentityNumberCountryValueEnum.BH);
        map.put("BD", EmployeeNationalIdentityNumberCountryValueEnum.BD);
        map.put("BB", EmployeeNationalIdentityNumberCountryValueEnum.BB);
        map.put("BY", EmployeeNationalIdentityNumberCountryValueEnum.BY);
        map.put("BE", EmployeeNationalIdentityNumberCountryValueEnum.BE);
        map.put("BZ", EmployeeNationalIdentityNumberCountryValueEnum.BZ);
        map.put("BJ", EmployeeNationalIdentityNumberCountryValueEnum.BJ);
        map.put("BM", EmployeeNationalIdentityNumberCountryValueEnum.BM);
        map.put("BT", EmployeeNationalIdentityNumberCountryValueEnum.BT);
        map.put("BO", EmployeeNationalIdentityNumberCountryValueEnum.BO);
        map.put("BQ", EmployeeNationalIdentityNumberCountryValueEnum.BQ);
        map.put("BA", EmployeeNationalIdentityNumberCountryValueEnum.BA);
        map.put("BW", EmployeeNationalIdentityNumberCountryValueEnum.BW);
        map.put("BV", EmployeeNationalIdentityNumberCountryValueEnum.BV);
        map.put("BR", EmployeeNationalIdentityNumberCountryValueEnum.BR);
        map.put("IO", EmployeeNationalIdentityNumberCountryValueEnum.IO);
        map.put("BN", EmployeeNationalIdentityNumberCountryValueEnum.BN);
        map.put("BG", EmployeeNationalIdentityNumberCountryValueEnum.BG);
        map.put("BF", EmployeeNationalIdentityNumberCountryValueEnum.BF);
        map.put("BI", EmployeeNationalIdentityNumberCountryValueEnum.BI);
        map.put("KH", EmployeeNationalIdentityNumberCountryValueEnum.KH);
        map.put("CM", EmployeeNationalIdentityNumberCountryValueEnum.CM);
        map.put("CA", EmployeeNationalIdentityNumberCountryValueEnum.CA);
        map.put("CV", EmployeeNationalIdentityNumberCountryValueEnum.CV);
        map.put("KY", EmployeeNationalIdentityNumberCountryValueEnum.KY);
        map.put("CF", EmployeeNationalIdentityNumberCountryValueEnum.CF);
        map.put("TD", EmployeeNationalIdentityNumberCountryValueEnum.TD);
        map.put("CL", EmployeeNationalIdentityNumberCountryValueEnum.CL);
        map.put("CN", EmployeeNationalIdentityNumberCountryValueEnum.CN);
        map.put("CX", EmployeeNationalIdentityNumberCountryValueEnum.CX);
        map.put("CC", EmployeeNationalIdentityNumberCountryValueEnum.CC);
        map.put("CO", EmployeeNationalIdentityNumberCountryValueEnum.CO);
        map.put("KM", EmployeeNationalIdentityNumberCountryValueEnum.KM);
        map.put("CG", EmployeeNationalIdentityNumberCountryValueEnum.CG);
        map.put("CD", EmployeeNationalIdentityNumberCountryValueEnum.CD);
        map.put("CK", EmployeeNationalIdentityNumberCountryValueEnum.CK);
        map.put("CR", EmployeeNationalIdentityNumberCountryValueEnum.CR);
        map.put("HR", EmployeeNationalIdentityNumberCountryValueEnum.HR);
        map.put("CU", EmployeeNationalIdentityNumberCountryValueEnum.CU);
        map.put("CW", EmployeeNationalIdentityNumberCountryValueEnum.CW);
        map.put("CY", EmployeeNationalIdentityNumberCountryValueEnum.CY);
        map.put("CZ", EmployeeNationalIdentityNumberCountryValueEnum.CZ);
        map.put("CI", EmployeeNationalIdentityNumberCountryValueEnum.CI);
        map.put("DK", EmployeeNationalIdentityNumberCountryValueEnum.DK);
        map.put("DJ", EmployeeNationalIdentityNumberCountryValueEnum.DJ);
        map.put("DM", EmployeeNationalIdentityNumberCountryValueEnum.DM);
        map.put("DO", EmployeeNationalIdentityNumberCountryValueEnum.DO);
        map.put("EC", EmployeeNationalIdentityNumberCountryValueEnum.EC);
        map.put("EG", EmployeeNationalIdentityNumberCountryValueEnum.EG);
        map.put("SV", EmployeeNationalIdentityNumberCountryValueEnum.SV);
        map.put("GQ", EmployeeNationalIdentityNumberCountryValueEnum.GQ);
        map.put("ER", EmployeeNationalIdentityNumberCountryValueEnum.ER);
        map.put("EE", EmployeeNationalIdentityNumberCountryValueEnum.EE);
        map.put("ET", EmployeeNationalIdentityNumberCountryValueEnum.ET);
        map.put("FK", EmployeeNationalIdentityNumberCountryValueEnum.FK);
        map.put("FO", EmployeeNationalIdentityNumberCountryValueEnum.FO);
        map.put("FJ", EmployeeNationalIdentityNumberCountryValueEnum.FJ);
        map.put("FI", EmployeeNationalIdentityNumberCountryValueEnum.FI);
        map.put("FR", EmployeeNationalIdentityNumberCountryValueEnum.FR);
        map.put("GF", EmployeeNationalIdentityNumberCountryValueEnum.GF);
        map.put("PF", EmployeeNationalIdentityNumberCountryValueEnum.PF);
        map.put("TF", EmployeeNationalIdentityNumberCountryValueEnum.TF);
        map.put("GA", EmployeeNationalIdentityNumberCountryValueEnum.GA);
        map.put("GM", EmployeeNationalIdentityNumberCountryValueEnum.GM);
        map.put("GE", EmployeeNationalIdentityNumberCountryValueEnum.GE);
        map.put("DE", EmployeeNationalIdentityNumberCountryValueEnum.DE);
        map.put("GH", EmployeeNationalIdentityNumberCountryValueEnum.GH);
        map.put("GI", EmployeeNationalIdentityNumberCountryValueEnum.GI);
        map.put("GR", EmployeeNationalIdentityNumberCountryValueEnum.GR);
        map.put("GL", EmployeeNationalIdentityNumberCountryValueEnum.GL);
        map.put("GD", EmployeeNationalIdentityNumberCountryValueEnum.GD);
        map.put("GP", EmployeeNationalIdentityNumberCountryValueEnum.GP);
        map.put("GU", EmployeeNationalIdentityNumberCountryValueEnum.GU);
        map.put("GT", EmployeeNationalIdentityNumberCountryValueEnum.GT);
        map.put("GG", EmployeeNationalIdentityNumberCountryValueEnum.GG);
        map.put("GN", EmployeeNationalIdentityNumberCountryValueEnum.GN);
        map.put("GW", EmployeeNationalIdentityNumberCountryValueEnum.GW);
        map.put("GY", EmployeeNationalIdentityNumberCountryValueEnum.GY);
        map.put("HT", EmployeeNationalIdentityNumberCountryValueEnum.HT);
        map.put("HM", EmployeeNationalIdentityNumberCountryValueEnum.HM);
        map.put("VA", EmployeeNationalIdentityNumberCountryValueEnum.VA);
        map.put("HN", EmployeeNationalIdentityNumberCountryValueEnum.HN);
        map.put("HK", EmployeeNationalIdentityNumberCountryValueEnum.HK);
        map.put("HU", EmployeeNationalIdentityNumberCountryValueEnum.HU);
        map.put("IS", EmployeeNationalIdentityNumberCountryValueEnum.IS);
        map.put("IN", EmployeeNationalIdentityNumberCountryValueEnum.IN);
        map.put("ID", EmployeeNationalIdentityNumberCountryValueEnum.ID);
        map.put("IR", EmployeeNationalIdentityNumberCountryValueEnum.IR);
        map.put("IQ", EmployeeNationalIdentityNumberCountryValueEnum.IQ);
        map.put("IE", EmployeeNationalIdentityNumberCountryValueEnum.IE);
        map.put("IM", EmployeeNationalIdentityNumberCountryValueEnum.IM);
        map.put("IL", EmployeeNationalIdentityNumberCountryValueEnum.IL);
        map.put("IT", EmployeeNationalIdentityNumberCountryValueEnum.IT);
        map.put("JM", EmployeeNationalIdentityNumberCountryValueEnum.JM);
        map.put("JP", EmployeeNationalIdentityNumberCountryValueEnum.JP);
        map.put("JE", EmployeeNationalIdentityNumberCountryValueEnum.JE);
        map.put("JO", EmployeeNationalIdentityNumberCountryValueEnum.JO);
        map.put("KZ", EmployeeNationalIdentityNumberCountryValueEnum.KZ);
        map.put("KE", EmployeeNationalIdentityNumberCountryValueEnum.KE);
        map.put("KI", EmployeeNationalIdentityNumberCountryValueEnum.KI);
        map.put("KP", EmployeeNationalIdentityNumberCountryValueEnum.KP);
        map.put("KR", EmployeeNationalIdentityNumberCountryValueEnum.KR);
        map.put("KW", EmployeeNationalIdentityNumberCountryValueEnum.KW);
        map.put("KG", EmployeeNationalIdentityNumberCountryValueEnum.KG);
        map.put("LA", EmployeeNationalIdentityNumberCountryValueEnum.LA);
        map.put("LV", EmployeeNationalIdentityNumberCountryValueEnum.LV);
        map.put("LB", EmployeeNationalIdentityNumberCountryValueEnum.LB);
        map.put("LS", EmployeeNationalIdentityNumberCountryValueEnum.LS);
        map.put("LR", EmployeeNationalIdentityNumberCountryValueEnum.LR);
        map.put("LY", EmployeeNationalIdentityNumberCountryValueEnum.LY);
        map.put("LI", EmployeeNationalIdentityNumberCountryValueEnum.LI);
        map.put("LT", EmployeeNationalIdentityNumberCountryValueEnum.LT);
        map.put("LU", EmployeeNationalIdentityNumberCountryValueEnum.LU);
        map.put("MO", EmployeeNationalIdentityNumberCountryValueEnum.MO);
        map.put("MK", EmployeeNationalIdentityNumberCountryValueEnum.MK);
        map.put("MG", EmployeeNationalIdentityNumberCountryValueEnum.MG);
        map.put("MW", EmployeeNationalIdentityNumberCountryValueEnum.MW);
        map.put("MY", EmployeeNationalIdentityNumberCountryValueEnum.MY);
        map.put("MV", EmployeeNationalIdentityNumberCountryValueEnum.MV);
        map.put("ML", EmployeeNationalIdentityNumberCountryValueEnum.ML);
        map.put("MT", EmployeeNationalIdentityNumberCountryValueEnum.MT);
        map.put("MH", EmployeeNationalIdentityNumberCountryValueEnum.MH);
        map.put("MQ", EmployeeNationalIdentityNumberCountryValueEnum.MQ);
        map.put("MR", EmployeeNationalIdentityNumberCountryValueEnum.MR);
        map.put("MU", EmployeeNationalIdentityNumberCountryValueEnum.MU);
        map.put("YT", EmployeeNationalIdentityNumberCountryValueEnum.YT);
        map.put("MX", EmployeeNationalIdentityNumberCountryValueEnum.MX);
        map.put("FM", EmployeeNationalIdentityNumberCountryValueEnum.FM);
        map.put("MD", EmployeeNationalIdentityNumberCountryValueEnum.MD);
        map.put("MC", EmployeeNationalIdentityNumberCountryValueEnum.MC);
        map.put("MN", EmployeeNationalIdentityNumberCountryValueEnum.MN);
        map.put("ME", EmployeeNationalIdentityNumberCountryValueEnum.ME);
        map.put("MS", EmployeeNationalIdentityNumberCountryValueEnum.MS);
        map.put("MA", EmployeeNationalIdentityNumberCountryValueEnum.MA);
        map.put("MZ", EmployeeNationalIdentityNumberCountryValueEnum.MZ);
        map.put("MM", EmployeeNationalIdentityNumberCountryValueEnum.MM);
        map.put("NA", EmployeeNationalIdentityNumberCountryValueEnum.NA);
        map.put("NR", EmployeeNationalIdentityNumberCountryValueEnum.NR);
        map.put("NP", EmployeeNationalIdentityNumberCountryValueEnum.NP);
        map.put("NL", EmployeeNationalIdentityNumberCountryValueEnum.NL);
        map.put("NC", EmployeeNationalIdentityNumberCountryValueEnum.NC);
        map.put("NZ", EmployeeNationalIdentityNumberCountryValueEnum.NZ);
        map.put("NI", EmployeeNationalIdentityNumberCountryValueEnum.NI);
        map.put("NE", EmployeeNationalIdentityNumberCountryValueEnum.NE);
        map.put("NG", EmployeeNationalIdentityNumberCountryValueEnum.NG);
        map.put("NU", EmployeeNationalIdentityNumberCountryValueEnum.NU);
        map.put("NF", EmployeeNationalIdentityNumberCountryValueEnum.NF);
        map.put("MP", EmployeeNationalIdentityNumberCountryValueEnum.MP);
        map.put("NO", EmployeeNationalIdentityNumberCountryValueEnum.NO);
        map.put("OM", EmployeeNationalIdentityNumberCountryValueEnum.OM);
        map.put("PK", EmployeeNationalIdentityNumberCountryValueEnum.PK);
        map.put("PW", EmployeeNationalIdentityNumberCountryValueEnum.PW);
        map.put("PS", EmployeeNationalIdentityNumberCountryValueEnum.PS);
        map.put("PA", EmployeeNationalIdentityNumberCountryValueEnum.PA);
        map.put("PG", EmployeeNationalIdentityNumberCountryValueEnum.PG);
        map.put("PY", EmployeeNationalIdentityNumberCountryValueEnum.PY);
        map.put("PE", EmployeeNationalIdentityNumberCountryValueEnum.PE);
        map.put("PH", EmployeeNationalIdentityNumberCountryValueEnum.PH);
        map.put("PN", EmployeeNationalIdentityNumberCountryValueEnum.PN);
        map.put("PL", EmployeeNationalIdentityNumberCountryValueEnum.PL);
        map.put("PT", EmployeeNationalIdentityNumberCountryValueEnum.PT);
        map.put("PR", EmployeeNationalIdentityNumberCountryValueEnum.PR);
        map.put("QA", EmployeeNationalIdentityNumberCountryValueEnum.QA);
        map.put("RO", EmployeeNationalIdentityNumberCountryValueEnum.RO);
        map.put("RU", EmployeeNationalIdentityNumberCountryValueEnum.RU);
        map.put("RW", EmployeeNationalIdentityNumberCountryValueEnum.RW);
        map.put("RE", EmployeeNationalIdentityNumberCountryValueEnum.RE);
        map.put("BL", EmployeeNationalIdentityNumberCountryValueEnum.BL);
        map.put("SH", EmployeeNationalIdentityNumberCountryValueEnum.SH);
        map.put("KN", EmployeeNationalIdentityNumberCountryValueEnum.KN);
        map.put("LC", EmployeeNationalIdentityNumberCountryValueEnum.LC);
        map.put("MF", EmployeeNationalIdentityNumberCountryValueEnum.MF);
        map.put("PM", EmployeeNationalIdentityNumberCountryValueEnum.PM);
        map.put("VC", EmployeeNationalIdentityNumberCountryValueEnum.VC);
        map.put("WS", EmployeeNationalIdentityNumberCountryValueEnum.WS);
        map.put("SM", EmployeeNationalIdentityNumberCountryValueEnum.SM);
        map.put("ST", EmployeeNationalIdentityNumberCountryValueEnum.ST);
        map.put("SA", EmployeeNationalIdentityNumberCountryValueEnum.SA);
        map.put("SN", EmployeeNationalIdentityNumberCountryValueEnum.SN);
        map.put("RS", EmployeeNationalIdentityNumberCountryValueEnum.RS);
        map.put("SC", EmployeeNationalIdentityNumberCountryValueEnum.SC);
        map.put("SL", EmployeeNationalIdentityNumberCountryValueEnum.SL);
        map.put("SG", EmployeeNationalIdentityNumberCountryValueEnum.SG);
        map.put("SX", EmployeeNationalIdentityNumberCountryValueEnum.SX);
        map.put("SK", EmployeeNationalIdentityNumberCountryValueEnum.SK);
        map.put("SI", EmployeeNationalIdentityNumberCountryValueEnum.SI);
        map.put("SB", EmployeeNationalIdentityNumberCountryValueEnum.SB);
        map.put("SO", EmployeeNationalIdentityNumberCountryValueEnum.SO);
        map.put("ZA", EmployeeNationalIdentityNumberCountryValueEnum.ZA);
        map.put("GS", EmployeeNationalIdentityNumberCountryValueEnum.GS);
        map.put("SS", EmployeeNationalIdentityNumberCountryValueEnum.SS);
        map.put("ES", EmployeeNationalIdentityNumberCountryValueEnum.ES);
        map.put("LK", EmployeeNationalIdentityNumberCountryValueEnum.LK);
        map.put("SD", EmployeeNationalIdentityNumberCountryValueEnum.SD);
        map.put("SR", EmployeeNationalIdentityNumberCountryValueEnum.SR);
        map.put("SJ", EmployeeNationalIdentityNumberCountryValueEnum.SJ);
        map.put("SZ", EmployeeNationalIdentityNumberCountryValueEnum.SZ);
        map.put("SE", EmployeeNationalIdentityNumberCountryValueEnum.SE);
        map.put("CH", EmployeeNationalIdentityNumberCountryValueEnum.CH);
        map.put("SY", EmployeeNationalIdentityNumberCountryValueEnum.SY);
        map.put("TW", EmployeeNationalIdentityNumberCountryValueEnum.TW);
        map.put("TJ", EmployeeNationalIdentityNumberCountryValueEnum.TJ);
        map.put("TZ", EmployeeNationalIdentityNumberCountryValueEnum.TZ);
        map.put("TH", EmployeeNationalIdentityNumberCountryValueEnum.TH);
        map.put("TL", EmployeeNationalIdentityNumberCountryValueEnum.TL);
        map.put("TG", EmployeeNationalIdentityNumberCountryValueEnum.TG);
        map.put("TK", EmployeeNationalIdentityNumberCountryValueEnum.TK);
        map.put("TO", EmployeeNationalIdentityNumberCountryValueEnum.TO);
        map.put("TT", EmployeeNationalIdentityNumberCountryValueEnum.TT);
        map.put("TN", EmployeeNationalIdentityNumberCountryValueEnum.TN);
        map.put("TR", EmployeeNationalIdentityNumberCountryValueEnum.TR);
        map.put("TM", EmployeeNationalIdentityNumberCountryValueEnum.TM);
        map.put("TC", EmployeeNationalIdentityNumberCountryValueEnum.TC);
        map.put("TV", EmployeeNationalIdentityNumberCountryValueEnum.TV);
        map.put("UG", EmployeeNationalIdentityNumberCountryValueEnum.UG);
        map.put("UA", EmployeeNationalIdentityNumberCountryValueEnum.UA);
        map.put("AE", EmployeeNationalIdentityNumberCountryValueEnum.AE);
        map.put("GB", EmployeeNationalIdentityNumberCountryValueEnum.GB);
        map.put("US", EmployeeNationalIdentityNumberCountryValueEnum.US);
        map.put("UM", EmployeeNationalIdentityNumberCountryValueEnum.UM);
        map.put("UY", EmployeeNationalIdentityNumberCountryValueEnum.UY);
        map.put("UZ", EmployeeNationalIdentityNumberCountryValueEnum.UZ);
        map.put("VU", EmployeeNationalIdentityNumberCountryValueEnum.VU);
        map.put("VE", EmployeeNationalIdentityNumberCountryValueEnum.VE);
        map.put("VN", EmployeeNationalIdentityNumberCountryValueEnum.VN);
        map.put("VG", EmployeeNationalIdentityNumberCountryValueEnum.VG);
        map.put("VI", EmployeeNationalIdentityNumberCountryValueEnum.VI);
        map.put("WF", EmployeeNationalIdentityNumberCountryValueEnum.WF);
        map.put("EH", EmployeeNationalIdentityNumberCountryValueEnum.EH);
        map.put("YE", EmployeeNationalIdentityNumberCountryValueEnum.YE);
        map.put("ZM", EmployeeNationalIdentityNumberCountryValueEnum.ZM);
        map.put("ZW", EmployeeNationalIdentityNumberCountryValueEnum.ZW);
        map.put("unmapped_value", EmployeeNationalIdentityNumberCountryValueEnum.UNMAPPED_VALUE);
        return map;
    }
    
    @SuppressWarnings("serial")
    public static final class _Serializer extends StdSerializer<EmployeeNationalIdentityNumberCountryValue> {

        protected _Serializer() {
            super(EmployeeNationalIdentityNumberCountryValue.class);
        }

        @Override
        public void serialize(EmployeeNationalIdentityNumberCountryValue value, JsonGenerator g, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            g.writeObject(value.value);
        }
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends StdDeserializer<EmployeeNationalIdentityNumberCountryValue> {

        protected _Deserializer() {
            super(EmployeeNationalIdentityNumberCountryValue.class);
        }

        @Override
        public EmployeeNationalIdentityNumberCountryValue deserialize(JsonParser p, DeserializationContext ctxt)
                throws IOException, JacksonException {
            String v = p.readValueAs(new TypeReference<String>() {});
            // use the factory method to ensure we get singletons
            return EmployeeNationalIdentityNumberCountryValue.of(v);
        }
    }
    
    public enum EmployeeNationalIdentityNumberCountryValueEnum {

        AF("AF"),
        AL("AL"),
        DZ("DZ"),
        AS("AS"),
        AD("AD"),
        AO("AO"),
        AI("AI"),
        AQ("AQ"),
        AG("AG"),
        AR("AR"),
        AM("AM"),
        AW("AW"),
        AU("AU"),
        AT("AT"),
        AZ("AZ"),
        BS("BS"),
        BH("BH"),
        BD("BD"),
        BB("BB"),
        BY("BY"),
        BE("BE"),
        BZ("BZ"),
        BJ("BJ"),
        BM("BM"),
        BT("BT"),
        BO("BO"),
        BQ("BQ"),
        BA("BA"),
        BW("BW"),
        BV("BV"),
        BR("BR"),
        IO("IO"),
        BN("BN"),
        BG("BG"),
        BF("BF"),
        BI("BI"),
        KH("KH"),
        CM("CM"),
        CA("CA"),
        CV("CV"),
        KY("KY"),
        CF("CF"),
        TD("TD"),
        CL("CL"),
        CN("CN"),
        CX("CX"),
        CC("CC"),
        CO("CO"),
        KM("KM"),
        CG("CG"),
        CD("CD"),
        CK("CK"),
        CR("CR"),
        HR("HR"),
        CU("CU"),
        CW("CW"),
        CY("CY"),
        CZ("CZ"),
        CI("CI"),
        DK("DK"),
        DJ("DJ"),
        DM("DM"),
        DO("DO"),
        EC("EC"),
        EG("EG"),
        SV("SV"),
        GQ("GQ"),
        ER("ER"),
        EE("EE"),
        ET("ET"),
        FK("FK"),
        FO("FO"),
        FJ("FJ"),
        FI("FI"),
        FR("FR"),
        GF("GF"),
        PF("PF"),
        TF("TF"),
        GA("GA"),
        GM("GM"),
        GE("GE"),
        DE("DE"),
        GH("GH"),
        GI("GI"),
        GR("GR"),
        GL("GL"),
        GD("GD"),
        GP("GP"),
        GU("GU"),
        GT("GT"),
        GG("GG"),
        GN("GN"),
        GW("GW"),
        GY("GY"),
        HT("HT"),
        HM("HM"),
        VA("VA"),
        HN("HN"),
        HK("HK"),
        HU("HU"),
        IS("IS"),
        IN("IN"),
        ID("ID"),
        IR("IR"),
        IQ("IQ"),
        IE("IE"),
        IM("IM"),
        IL("IL"),
        IT("IT"),
        JM("JM"),
        JP("JP"),
        JE("JE"),
        JO("JO"),
        KZ("KZ"),
        KE("KE"),
        KI("KI"),
        KP("KP"),
        KR("KR"),
        KW("KW"),
        KG("KG"),
        LA("LA"),
        LV("LV"),
        LB("LB"),
        LS("LS"),
        LR("LR"),
        LY("LY"),
        LI("LI"),
        LT("LT"),
        LU("LU"),
        MO("MO"),
        MK("MK"),
        MG("MG"),
        MW("MW"),
        MY("MY"),
        MV("MV"),
        ML("ML"),
        MT("MT"),
        MH("MH"),
        MQ("MQ"),
        MR("MR"),
        MU("MU"),
        YT("YT"),
        MX("MX"),
        FM("FM"),
        MD("MD"),
        MC("MC"),
        MN("MN"),
        ME("ME"),
        MS("MS"),
        MA("MA"),
        MZ("MZ"),
        MM("MM"),
        NA("NA"),
        NR("NR"),
        NP("NP"),
        NL("NL"),
        NC("NC"),
        NZ("NZ"),
        NI("NI"),
        NE("NE"),
        NG("NG"),
        NU("NU"),
        NF("NF"),
        MP("MP"),
        NO("NO"),
        OM("OM"),
        PK("PK"),
        PW("PW"),
        PS("PS"),
        PA("PA"),
        PG("PG"),
        PY("PY"),
        PE("PE"),
        PH("PH"),
        PN("PN"),
        PL("PL"),
        PT("PT"),
        PR("PR"),
        QA("QA"),
        RO("RO"),
        RU("RU"),
        RW("RW"),
        RE("RE"),
        BL("BL"),
        SH("SH"),
        KN("KN"),
        LC("LC"),
        MF("MF"),
        PM("PM"),
        VC("VC"),
        WS("WS"),
        SM("SM"),
        ST("ST"),
        SA("SA"),
        SN("SN"),
        RS("RS"),
        SC("SC"),
        SL("SL"),
        SG("SG"),
        SX("SX"),
        SK("SK"),
        SI("SI"),
        SB("SB"),
        SO("SO"),
        ZA("ZA"),
        GS("GS"),
        SS("SS"),
        ES("ES"),
        LK("LK"),
        SD("SD"),
        SR("SR"),
        SJ("SJ"),
        SZ("SZ"),
        SE("SE"),
        CH("CH"),
        SY("SY"),
        TW("TW"),
        TJ("TJ"),
        TZ("TZ"),
        TH("TH"),
        TL("TL"),
        TG("TG"),
        TK("TK"),
        TO("TO"),
        TT("TT"),
        TN("TN"),
        TR("TR"),
        TM("TM"),
        TC("TC"),
        TV("TV"),
        UG("UG"),
        UA("UA"),
        AE("AE"),
        GB("GB"),
        US("US"),
        UM("UM"),
        UY("UY"),
        UZ("UZ"),
        VU("VU"),
        VE("VE"),
        VN("VN"),
        VG("VG"),
        VI("VI"),
        WF("WF"),
        EH("EH"),
        YE("YE"),
        ZM("ZM"),
        ZW("ZW"),
        UNMAPPED_VALUE("unmapped_value"),;

        private final String value;

        private EmployeeNationalIdentityNumberCountryValueEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}
