/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.stackone.stackone_client_java.models.components;
import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


/**
 * <p>Wrapper class for an "open" enum. "Open" enums are those that are expected
 * to evolve (particularly with the addition of enum members over time). If an
 * open enum is used then the appearance of unexpected enum values (say in a 
 * response from an updated an API) will not bring about a runtime error thus 
 * ensuring that non-updated client versions can continue to work without error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe
 * cache is maintained to ensure that). As a consequence instances created with the 
 * same value will satisfy reference equality (via {@code ==}).
 * 
 * <p>This class is intended to emulate an enum (in terms of common usage and with 
 * reference equality) but with the ability to carry unknown values. Unfortunately
 * Java does not permit the use of an instance in a switch expression but you can 
 * use the {@code asEnum()} method (after dealing with the `Optional` appropriately).
 *
 */
@JsonDeserialize(using = HrisCreateEmployeeRequestDtoEmploymentStatusValue._Deserializer.class)
@JsonSerialize(using = HrisCreateEmployeeRequestDtoEmploymentStatusValue._Serializer.class)
public class HrisCreateEmployeeRequestDtoEmploymentStatusValue {

    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue ACTIVE = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("active");
    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue PENDING = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("pending");
    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue TERMINATED = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("terminated");
    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue LEAVE = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("leave");
    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue INACTIVE = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("inactive");
    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue UNKNOWN = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("unknown");
    public static final HrisCreateEmployeeRequestDtoEmploymentStatusValue UNMAPPED_VALUE = new HrisCreateEmployeeRequestDtoEmploymentStatusValue("unmapped_value");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, HrisCreateEmployeeRequestDtoEmploymentStatusValue> values = createValuesMap();
    private static final Map<String, HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum> enums = createEnumsMap();

    private final String value;

    private HrisCreateEmployeeRequestDtoEmploymentStatusValue(String value) {
        this.value = value;
    }

    /**
     * Returns a HrisCreateEmployeeRequestDtoEmploymentStatusValue with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as HrisCreateEmployeeRequestDtoEmploymentStatusValue
     */ 
    public static HrisCreateEmployeeRequestDtoEmploymentStatusValue of(String value) {
        synchronized (HrisCreateEmployeeRequestDtoEmploymentStatusValue.class) {
            return values.computeIfAbsent(value, v -> new HrisCreateEmployeeRequestDtoEmploymentStatusValue(v));
        }
    }

    public String value() {
        return value;
    }

    public Optional<HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        HrisCreateEmployeeRequestDtoEmploymentStatusValue other = (HrisCreateEmployeeRequestDtoEmploymentStatusValue) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "HrisCreateEmployeeRequestDtoEmploymentStatusValue [value=" + value + "]";
    }

    // return an array just like an enum
    public static HrisCreateEmployeeRequestDtoEmploymentStatusValue[] values() {
        synchronized (HrisCreateEmployeeRequestDtoEmploymentStatusValue.class) {
            return values.values().toArray(new HrisCreateEmployeeRequestDtoEmploymentStatusValue[] {});
        }
    }

    private static final Map<String, HrisCreateEmployeeRequestDtoEmploymentStatusValue> createValuesMap() {
        Map<String, HrisCreateEmployeeRequestDtoEmploymentStatusValue> map = new LinkedHashMap<>();
        map.put("active", ACTIVE);
        map.put("pending", PENDING);
        map.put("terminated", TERMINATED);
        map.put("leave", LEAVE);
        map.put("inactive", INACTIVE);
        map.put("unknown", UNKNOWN);
        map.put("unmapped_value", UNMAPPED_VALUE);
        return map;
    }

    private static final Map<String, HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum> createEnumsMap() {
        Map<String, HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum> map = new HashMap<>();
        map.put("active", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.ACTIVE);
        map.put("pending", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.PENDING);
        map.put("terminated", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.TERMINATED);
        map.put("leave", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.LEAVE);
        map.put("inactive", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.INACTIVE);
        map.put("unknown", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.UNKNOWN);
        map.put("unmapped_value", HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum.UNMAPPED_VALUE);
        return map;
    }
    
    @SuppressWarnings("serial")
    public static final class _Serializer extends StdSerializer<HrisCreateEmployeeRequestDtoEmploymentStatusValue> {

        protected _Serializer() {
            super(HrisCreateEmployeeRequestDtoEmploymentStatusValue.class);
        }

        @Override
        public void serialize(HrisCreateEmployeeRequestDtoEmploymentStatusValue value, JsonGenerator g, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            g.writeObject(value.value);
        }
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends StdDeserializer<HrisCreateEmployeeRequestDtoEmploymentStatusValue> {

        protected _Deserializer() {
            super(HrisCreateEmployeeRequestDtoEmploymentStatusValue.class);
        }

        @Override
        public HrisCreateEmployeeRequestDtoEmploymentStatusValue deserialize(JsonParser p, DeserializationContext ctxt)
                throws IOException, JacksonException {
            String v = p.readValueAs(new TypeReference<String>() {});
            // use the factory method to ensure we get singletons
            return HrisCreateEmployeeRequestDtoEmploymentStatusValue.of(v);
        }
    }
    
    public enum HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum {

        ACTIVE("active"),
        PENDING("pending"),
        TERMINATED("terminated"),
        LEAVE("leave"),
        INACTIVE("inactive"),
        UNKNOWN("unknown"),
        UNMAPPED_VALUE("unmapped_value"),;

        private final String value;

        private HrisCreateEmployeeRequestDtoEmploymentStatusValueEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}
