/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * HrisCreateEmploymentRequestDtoWorkTimeValue
 * 
 * <p>The unified value for the period.
 */
public class HrisCreateEmploymentRequestDtoWorkTimeValue {

    public static final HrisCreateEmploymentRequestDtoWorkTimeValue DAY = new HrisCreateEmploymentRequestDtoWorkTimeValue("day");
    public static final HrisCreateEmploymentRequestDtoWorkTimeValue WEEK = new HrisCreateEmploymentRequestDtoWorkTimeValue("week");
    public static final HrisCreateEmploymentRequestDtoWorkTimeValue MONTH = new HrisCreateEmploymentRequestDtoWorkTimeValue("month");
    public static final HrisCreateEmploymentRequestDtoWorkTimeValue YEAR = new HrisCreateEmploymentRequestDtoWorkTimeValue("year");
    public static final HrisCreateEmploymentRequestDtoWorkTimeValue UNMAPPED_VALUE = new HrisCreateEmploymentRequestDtoWorkTimeValue("unmapped_value");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, HrisCreateEmploymentRequestDtoWorkTimeValue> values = createValuesMap();
    private static final Map<String, HrisCreateEmploymentRequestDtoWorkTimeValueEnum> enums = createEnumsMap();

    private final String value;

    private HrisCreateEmploymentRequestDtoWorkTimeValue(String value) {
        this.value = value;
    }

    /**
     * Returns a HrisCreateEmploymentRequestDtoWorkTimeValue with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as HrisCreateEmploymentRequestDtoWorkTimeValue
     */ 
    @JsonCreator
    public static HrisCreateEmploymentRequestDtoWorkTimeValue of(String value) {
        synchronized (HrisCreateEmploymentRequestDtoWorkTimeValue.class) {
            return values.computeIfAbsent(value, v -> new HrisCreateEmploymentRequestDtoWorkTimeValue(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<HrisCreateEmploymentRequestDtoWorkTimeValueEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        HrisCreateEmploymentRequestDtoWorkTimeValue other = (HrisCreateEmploymentRequestDtoWorkTimeValue) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "HrisCreateEmploymentRequestDtoWorkTimeValue [value=" + value + "]";
    }

    // return an array just like an enum
    public static HrisCreateEmploymentRequestDtoWorkTimeValue[] values() {
        synchronized (HrisCreateEmploymentRequestDtoWorkTimeValue.class) {
            return values.values().toArray(new HrisCreateEmploymentRequestDtoWorkTimeValue[] {});
        }
    }

    private static final Map<String, HrisCreateEmploymentRequestDtoWorkTimeValue> createValuesMap() {
        Map<String, HrisCreateEmploymentRequestDtoWorkTimeValue> map = new LinkedHashMap<>();
        map.put("day", DAY);
        map.put("week", WEEK);
        map.put("month", MONTH);
        map.put("year", YEAR);
        map.put("unmapped_value", UNMAPPED_VALUE);
        return map;
    }

    private static final Map<String, HrisCreateEmploymentRequestDtoWorkTimeValueEnum> createEnumsMap() {
        Map<String, HrisCreateEmploymentRequestDtoWorkTimeValueEnum> map = new HashMap<>();
        map.put("day", HrisCreateEmploymentRequestDtoWorkTimeValueEnum.DAY);
        map.put("week", HrisCreateEmploymentRequestDtoWorkTimeValueEnum.WEEK);
        map.put("month", HrisCreateEmploymentRequestDtoWorkTimeValueEnum.MONTH);
        map.put("year", HrisCreateEmploymentRequestDtoWorkTimeValueEnum.YEAR);
        map.put("unmapped_value", HrisCreateEmploymentRequestDtoWorkTimeValueEnum.UNMAPPED_VALUE);
        return map;
    }
    
    
    public enum HrisCreateEmploymentRequestDtoWorkTimeValueEnum {

        DAY("day"),
        WEEK("week"),
        MONTH("month"),
        YEAR("year"),
        UNMAPPED_VALUE("unmapped_value"),;

        private final String value;

        private HrisCreateEmploymentRequestDtoWorkTimeValueEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

