/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * HrisUpdateEmployeeRequestDtoEmploymentTypeType
 * 
 * <p>The type of employment (e.g., contractor, permanent)
 */
public class HrisUpdateEmployeeRequestDtoEmploymentTypeType {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue> value;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("source_value")
    private JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue> sourceValue;

    @JsonCreator
    public HrisUpdateEmployeeRequestDtoEmploymentTypeType(
            @JsonProperty("value") JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue> value,
            @JsonProperty("source_value") JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue> sourceValue) {
        Utils.checkNotNull(value, "value");
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.value = value;
        this.sourceValue = sourceValue;
    }
    
    public HrisUpdateEmployeeRequestDtoEmploymentTypeType() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue> value() {
        return (JsonNullable<HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue>) value;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue> sourceValue() {
        return (JsonNullable<HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue>) sourceValue;
    }

    public static Builder builder() {
        return new Builder();
    }


    public HrisUpdateEmployeeRequestDtoEmploymentTypeType withValue(HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue value) {
        Utils.checkNotNull(value, "value");
        this.value = JsonNullable.of(value);
        return this;
    }

    public HrisUpdateEmployeeRequestDtoEmploymentTypeType withValue(JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }

    public HrisUpdateEmployeeRequestDtoEmploymentTypeType withSourceValue(HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue sourceValue) {
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.sourceValue = JsonNullable.of(sourceValue);
        return this;
    }

    public HrisUpdateEmployeeRequestDtoEmploymentTypeType withSourceValue(JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue> sourceValue) {
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.sourceValue = sourceValue;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HrisUpdateEmployeeRequestDtoEmploymentTypeType other = (HrisUpdateEmployeeRequestDtoEmploymentTypeType) o;
        return 
            Utils.enhancedDeepEquals(this.value, other.value) &&
            Utils.enhancedDeepEquals(this.sourceValue, other.sourceValue);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            value, sourceValue);
    }
    
    @Override
    public String toString() {
        return Utils.toString(HrisUpdateEmployeeRequestDtoEmploymentTypeType.class,
                "value", value,
                "sourceValue", sourceValue);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue> value = JsonNullable.undefined();

        private JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue> sourceValue = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder value(HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue value) {
            Utils.checkNotNull(value, "value");
            this.value = JsonNullable.of(value);
            return this;
        }

        public Builder value(JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeValue> value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }


        public Builder sourceValue(HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue sourceValue) {
            Utils.checkNotNull(sourceValue, "sourceValue");
            this.sourceValue = JsonNullable.of(sourceValue);
            return this;
        }

        public Builder sourceValue(JsonNullable<? extends HrisUpdateEmployeeRequestDtoEmploymentTypeTypeSourceValue> sourceValue) {
            Utils.checkNotNull(sourceValue, "sourceValue");
            this.sourceValue = sourceValue;
            return this;
        }

        public HrisUpdateEmployeeRequestDtoEmploymentTypeType build() {

            return new HrisUpdateEmployeeRequestDtoEmploymentTypeType(
                value, sourceValue);
        }

    }
}
