/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class HrisCreateWorkEligibilityRequestDtoType {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeValue> value;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("source_value")
    private JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeSourceValue> sourceValue;

    @JsonCreator
    public HrisCreateWorkEligibilityRequestDtoType(
            @JsonProperty("value") JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeValue> value,
            @JsonProperty("source_value") JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeSourceValue> sourceValue) {
        Utils.checkNotNull(value, "value");
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.value = value;
        this.sourceValue = sourceValue;
    }
    
    public HrisCreateWorkEligibilityRequestDtoType() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<HrisCreateWorkEligibilityRequestDtoTypeValue> value() {
        return (JsonNullable<HrisCreateWorkEligibilityRequestDtoTypeValue>) value;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<HrisCreateWorkEligibilityRequestDtoTypeSourceValue> sourceValue() {
        return (JsonNullable<HrisCreateWorkEligibilityRequestDtoTypeSourceValue>) sourceValue;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public HrisCreateWorkEligibilityRequestDtoType withValue(HrisCreateWorkEligibilityRequestDtoTypeValue value) {
        Utils.checkNotNull(value, "value");
        this.value = JsonNullable.of(value);
        return this;
    }

    public HrisCreateWorkEligibilityRequestDtoType withValue(JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeValue> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }

    public HrisCreateWorkEligibilityRequestDtoType withSourceValue(HrisCreateWorkEligibilityRequestDtoTypeSourceValue sourceValue) {
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.sourceValue = JsonNullable.of(sourceValue);
        return this;
    }

    public HrisCreateWorkEligibilityRequestDtoType withSourceValue(JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeSourceValue> sourceValue) {
        Utils.checkNotNull(sourceValue, "sourceValue");
        this.sourceValue = sourceValue;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HrisCreateWorkEligibilityRequestDtoType other = (HrisCreateWorkEligibilityRequestDtoType) o;
        return 
            Objects.deepEquals(this.value, other.value) &&
            Objects.deepEquals(this.sourceValue, other.sourceValue);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            value,
            sourceValue);
    }
    
    @Override
    public String toString() {
        return Utils.toString(HrisCreateWorkEligibilityRequestDtoType.class,
                "value", value,
                "sourceValue", sourceValue);
    }
    
    public final static class Builder {
 
        private JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeValue> value = JsonNullable.undefined();
 
        private JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeSourceValue> sourceValue = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder value(HrisCreateWorkEligibilityRequestDtoTypeValue value) {
            Utils.checkNotNull(value, "value");
            this.value = JsonNullable.of(value);
            return this;
        }

        public Builder value(JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeValue> value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }

        public Builder sourceValue(HrisCreateWorkEligibilityRequestDtoTypeSourceValue sourceValue) {
            Utils.checkNotNull(sourceValue, "sourceValue");
            this.sourceValue = JsonNullable.of(sourceValue);
            return this;
        }

        public Builder sourceValue(JsonNullable<? extends HrisCreateWorkEligibilityRequestDtoTypeSourceValue> sourceValue) {
            Utils.checkNotNull(sourceValue, "sourceValue");
            this.sourceValue = sourceValue;
            return this;
        }
        
        public HrisCreateWorkEligibilityRequestDtoType build() {
            return new HrisCreateWorkEligibilityRequestDtoType(
                value,
                sourceValue);
        }
    }
}
