/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import org.openapitools.jackson.nullable.JsonNullable;


public class JobPostingCompensation {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private JsonNullable<String> title;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private JsonNullable<? extends JobPostingCompensationType> type;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pay_period")
    private JsonNullable<? extends JobPostingCompensationPayPeriod> payPeriod;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pay_frequency")
    private JsonNullable<? extends JobPostingCompensationPayFrequency> payFrequency;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currency")
    private JsonNullable<String> currency;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private JsonNullable<String> value;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("min_value_range")
    private JsonNullable<String> minValueRange;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max_value_range")
    private JsonNullable<String> maxValueRange;

    @JsonCreator
    public JobPostingCompensation(
            @JsonProperty("title") JsonNullable<String> title,
            @JsonProperty("type") JsonNullable<? extends JobPostingCompensationType> type,
            @JsonProperty("pay_period") JsonNullable<? extends JobPostingCompensationPayPeriod> payPeriod,
            @JsonProperty("pay_frequency") JsonNullable<? extends JobPostingCompensationPayFrequency> payFrequency,
            @JsonProperty("currency") JsonNullable<String> currency,
            @JsonProperty("value") JsonNullable<String> value,
            @JsonProperty("min_value_range") JsonNullable<String> minValueRange,
            @JsonProperty("max_value_range") JsonNullable<String> maxValueRange) {
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(payPeriod, "payPeriod");
        Utils.checkNotNull(payFrequency, "payFrequency");
        Utils.checkNotNull(currency, "currency");
        Utils.checkNotNull(value, "value");
        Utils.checkNotNull(minValueRange, "minValueRange");
        Utils.checkNotNull(maxValueRange, "maxValueRange");
        this.title = title;
        this.type = type;
        this.payPeriod = payPeriod;
        this.payFrequency = payFrequency;
        this.currency = currency;
        this.value = value;
        this.minValueRange = minValueRange;
        this.maxValueRange = maxValueRange;
    }
    
    public JobPostingCompensation() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public JsonNullable<String> title() {
        return title;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<JobPostingCompensationType> type() {
        return (JsonNullable<JobPostingCompensationType>) type;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<JobPostingCompensationPayPeriod> payPeriod() {
        return (JsonNullable<JobPostingCompensationPayPeriod>) payPeriod;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<JobPostingCompensationPayFrequency> payFrequency() {
        return (JsonNullable<JobPostingCompensationPayFrequency>) payFrequency;
    }

    @JsonIgnore
    public JsonNullable<String> currency() {
        return currency;
    }

    @JsonIgnore
    public JsonNullable<String> value() {
        return value;
    }

    @JsonIgnore
    public JsonNullable<String> minValueRange() {
        return minValueRange;
    }

    @JsonIgnore
    public JsonNullable<String> maxValueRange() {
        return maxValueRange;
    }

    public static Builder builder() {
        return new Builder();
    }


    public JobPostingCompensation withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = JsonNullable.of(title);
        return this;
    }

    public JobPostingCompensation withTitle(JsonNullable<String> title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    public JobPostingCompensation withType(JobPostingCompensationType type) {
        Utils.checkNotNull(type, "type");
        this.type = JsonNullable.of(type);
        return this;
    }

    public JobPostingCompensation withType(JsonNullable<? extends JobPostingCompensationType> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    public JobPostingCompensation withPayPeriod(JobPostingCompensationPayPeriod payPeriod) {
        Utils.checkNotNull(payPeriod, "payPeriod");
        this.payPeriod = JsonNullable.of(payPeriod);
        return this;
    }

    public JobPostingCompensation withPayPeriod(JsonNullable<? extends JobPostingCompensationPayPeriod> payPeriod) {
        Utils.checkNotNull(payPeriod, "payPeriod");
        this.payPeriod = payPeriod;
        return this;
    }

    public JobPostingCompensation withPayFrequency(JobPostingCompensationPayFrequency payFrequency) {
        Utils.checkNotNull(payFrequency, "payFrequency");
        this.payFrequency = JsonNullable.of(payFrequency);
        return this;
    }

    public JobPostingCompensation withPayFrequency(JsonNullable<? extends JobPostingCompensationPayFrequency> payFrequency) {
        Utils.checkNotNull(payFrequency, "payFrequency");
        this.payFrequency = payFrequency;
        return this;
    }

    public JobPostingCompensation withCurrency(String currency) {
        Utils.checkNotNull(currency, "currency");
        this.currency = JsonNullable.of(currency);
        return this;
    }

    public JobPostingCompensation withCurrency(JsonNullable<String> currency) {
        Utils.checkNotNull(currency, "currency");
        this.currency = currency;
        return this;
    }

    public JobPostingCompensation withValue(String value) {
        Utils.checkNotNull(value, "value");
        this.value = JsonNullable.of(value);
        return this;
    }

    public JobPostingCompensation withValue(JsonNullable<String> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }

    public JobPostingCompensation withMinValueRange(String minValueRange) {
        Utils.checkNotNull(minValueRange, "minValueRange");
        this.minValueRange = JsonNullable.of(minValueRange);
        return this;
    }

    public JobPostingCompensation withMinValueRange(JsonNullable<String> minValueRange) {
        Utils.checkNotNull(minValueRange, "minValueRange");
        this.minValueRange = minValueRange;
        return this;
    }

    public JobPostingCompensation withMaxValueRange(String maxValueRange) {
        Utils.checkNotNull(maxValueRange, "maxValueRange");
        this.maxValueRange = JsonNullable.of(maxValueRange);
        return this;
    }

    public JobPostingCompensation withMaxValueRange(JsonNullable<String> maxValueRange) {
        Utils.checkNotNull(maxValueRange, "maxValueRange");
        this.maxValueRange = maxValueRange;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobPostingCompensation other = (JobPostingCompensation) o;
        return 
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.payPeriod, other.payPeriod) &&
            Utils.enhancedDeepEquals(this.payFrequency, other.payFrequency) &&
            Utils.enhancedDeepEquals(this.currency, other.currency) &&
            Utils.enhancedDeepEquals(this.value, other.value) &&
            Utils.enhancedDeepEquals(this.minValueRange, other.minValueRange) &&
            Utils.enhancedDeepEquals(this.maxValueRange, other.maxValueRange);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            title, type, payPeriod,
            payFrequency, currency, value,
            minValueRange, maxValueRange);
    }
    
    @Override
    public String toString() {
        return Utils.toString(JobPostingCompensation.class,
                "title", title,
                "type", type,
                "payPeriod", payPeriod,
                "payFrequency", payFrequency,
                "currency", currency,
                "value", value,
                "minValueRange", minValueRange,
                "maxValueRange", maxValueRange);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> title = JsonNullable.undefined();

        private JsonNullable<? extends JobPostingCompensationType> type = JsonNullable.undefined();

        private JsonNullable<? extends JobPostingCompensationPayPeriod> payPeriod = JsonNullable.undefined();

        private JsonNullable<? extends JobPostingCompensationPayFrequency> payFrequency = JsonNullable.undefined();

        private JsonNullable<String> currency = JsonNullable.undefined();

        private JsonNullable<String> value = JsonNullable.undefined();

        private JsonNullable<String> minValueRange = JsonNullable.undefined();

        private JsonNullable<String> maxValueRange = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = JsonNullable.of(title);
            return this;
        }

        public Builder title(JsonNullable<String> title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }


        public Builder type(JobPostingCompensationType type) {
            Utils.checkNotNull(type, "type");
            this.type = JsonNullable.of(type);
            return this;
        }

        public Builder type(JsonNullable<? extends JobPostingCompensationType> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        public Builder payPeriod(JobPostingCompensationPayPeriod payPeriod) {
            Utils.checkNotNull(payPeriod, "payPeriod");
            this.payPeriod = JsonNullable.of(payPeriod);
            return this;
        }

        public Builder payPeriod(JsonNullable<? extends JobPostingCompensationPayPeriod> payPeriod) {
            Utils.checkNotNull(payPeriod, "payPeriod");
            this.payPeriod = payPeriod;
            return this;
        }


        public Builder payFrequency(JobPostingCompensationPayFrequency payFrequency) {
            Utils.checkNotNull(payFrequency, "payFrequency");
            this.payFrequency = JsonNullable.of(payFrequency);
            return this;
        }

        public Builder payFrequency(JsonNullable<? extends JobPostingCompensationPayFrequency> payFrequency) {
            Utils.checkNotNull(payFrequency, "payFrequency");
            this.payFrequency = payFrequency;
            return this;
        }


        public Builder currency(String currency) {
            Utils.checkNotNull(currency, "currency");
            this.currency = JsonNullable.of(currency);
            return this;
        }

        public Builder currency(JsonNullable<String> currency) {
            Utils.checkNotNull(currency, "currency");
            this.currency = currency;
            return this;
        }


        public Builder value(String value) {
            Utils.checkNotNull(value, "value");
            this.value = JsonNullable.of(value);
            return this;
        }

        public Builder value(JsonNullable<String> value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }


        public Builder minValueRange(String minValueRange) {
            Utils.checkNotNull(minValueRange, "minValueRange");
            this.minValueRange = JsonNullable.of(minValueRange);
            return this;
        }

        public Builder minValueRange(JsonNullable<String> minValueRange) {
            Utils.checkNotNull(minValueRange, "minValueRange");
            this.minValueRange = minValueRange;
            return this;
        }


        public Builder maxValueRange(String maxValueRange) {
            Utils.checkNotNull(maxValueRange, "maxValueRange");
            this.maxValueRange = JsonNullable.of(maxValueRange);
            return this;
        }

        public Builder maxValueRange(JsonNullable<String> maxValueRange) {
            Utils.checkNotNull(maxValueRange, "maxValueRange");
            this.maxValueRange = maxValueRange;
            return this;
        }

        public JobPostingCompensation build() {

            return new JobPostingCompensation(
                title, type, payPeriod,
                payFrequency, currency, value,
                minValueRange, maxValueRange);
        }

    }
}
