/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * TicketingTicketUpdateRequestDtoStatusValue
 * 
 * <p>The type of this status
 */
public class TicketingTicketUpdateRequestDtoStatusValue {

    public static final TicketingTicketUpdateRequestDtoStatusValue TO_DO = new TicketingTicketUpdateRequestDtoStatusValue("to-do");
    public static final TicketingTicketUpdateRequestDtoStatusValue IN_PROGRESS = new TicketingTicketUpdateRequestDtoStatusValue("in-progress");
    public static final TicketingTicketUpdateRequestDtoStatusValue CLOSED = new TicketingTicketUpdateRequestDtoStatusValue("closed");
    public static final TicketingTicketUpdateRequestDtoStatusValue UNMAPPED_VALUE = new TicketingTicketUpdateRequestDtoStatusValue("unmapped_value");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, TicketingTicketUpdateRequestDtoStatusValue> values = createValuesMap();
    private static final Map<String, TicketingTicketUpdateRequestDtoStatusValueEnum> enums = createEnumsMap();

    private final String value;

    private TicketingTicketUpdateRequestDtoStatusValue(String value) {
        this.value = value;
    }

    /**
     * Returns a TicketingTicketUpdateRequestDtoStatusValue with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as TicketingTicketUpdateRequestDtoStatusValue
     */ 
    @JsonCreator
    public static TicketingTicketUpdateRequestDtoStatusValue of(String value) {
        synchronized (TicketingTicketUpdateRequestDtoStatusValue.class) {
            return values.computeIfAbsent(value, v -> new TicketingTicketUpdateRequestDtoStatusValue(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<TicketingTicketUpdateRequestDtoStatusValueEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TicketingTicketUpdateRequestDtoStatusValue other = (TicketingTicketUpdateRequestDtoStatusValue) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "TicketingTicketUpdateRequestDtoStatusValue [value=" + value + "]";
    }

    // return an array just like an enum
    public static TicketingTicketUpdateRequestDtoStatusValue[] values() {
        synchronized (TicketingTicketUpdateRequestDtoStatusValue.class) {
            return values.values().toArray(new TicketingTicketUpdateRequestDtoStatusValue[] {});
        }
    }

    private static final Map<String, TicketingTicketUpdateRequestDtoStatusValue> createValuesMap() {
        Map<String, TicketingTicketUpdateRequestDtoStatusValue> map = new LinkedHashMap<>();
        map.put("to-do", TO_DO);
        map.put("in-progress", IN_PROGRESS);
        map.put("closed", CLOSED);
        map.put("unmapped_value", UNMAPPED_VALUE);
        return map;
    }

    private static final Map<String, TicketingTicketUpdateRequestDtoStatusValueEnum> createEnumsMap() {
        Map<String, TicketingTicketUpdateRequestDtoStatusValueEnum> map = new HashMap<>();
        map.put("to-do", TicketingTicketUpdateRequestDtoStatusValueEnum.TO_DO);
        map.put("in-progress", TicketingTicketUpdateRequestDtoStatusValueEnum.IN_PROGRESS);
        map.put("closed", TicketingTicketUpdateRequestDtoStatusValueEnum.CLOSED);
        map.put("unmapped_value", TicketingTicketUpdateRequestDtoStatusValueEnum.UNMAPPED_VALUE);
        return map;
    }
    
    
    public enum TicketingTicketUpdateRequestDtoStatusValueEnum {

        TO_DO("to-do"),
        IN_PROGRESS("in-progress"),
        CLOSED("closed"),
        UNMAPPED_VALUE("unmapped_value"),;

        private final String value;

        private TicketingTicketUpdateRequestDtoStatusValueEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

