/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.operations.async;

import static com.stackone.stackone_client_java.operations.Operations.AsyncRequestOperation;

import com.stackone.stackone_client_java.SDKConfiguration;
import com.stackone.stackone_client_java.models.components.HrisDocumentsUploadRequestDto;
import com.stackone.stackone_client_java.models.operations.HrisUploadEmployeeDocumentRequest;
import com.stackone.stackone_client_java.operations.HrisUploadEmployeeDocument;
import com.stackone.stackone_client_java.utils.Headers;
import com.stackone.stackone_client_java.utils.Options;
import com.stackone.stackone_client_java.utils.RetryConfig;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class HrisUploadEmployeeDocumentRequestBuilder {

    private String xAccountId;
    private String id;
    private HrisDocumentsUploadRequestDto hrisDocumentsUploadRequestDto;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public HrisUploadEmployeeDocumentRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public HrisUploadEmployeeDocumentRequestBuilder xAccountId(String xAccountId) {
        Utils.checkNotNull(xAccountId, "xAccountId");
        this.xAccountId = xAccountId;
        return this;
    }

    public HrisUploadEmployeeDocumentRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public HrisUploadEmployeeDocumentRequestBuilder hrisDocumentsUploadRequestDto(HrisDocumentsUploadRequestDto hrisDocumentsUploadRequestDto) {
        Utils.checkNotNull(hrisDocumentsUploadRequestDto, "hrisDocumentsUploadRequestDto");
        this.hrisDocumentsUploadRequestDto = hrisDocumentsUploadRequestDto;
        return this;
    }
                
    public HrisUploadEmployeeDocumentRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public HrisUploadEmployeeDocumentRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private HrisUploadEmployeeDocumentRequest buildRequest() {

        HrisUploadEmployeeDocumentRequest request = new HrisUploadEmployeeDocumentRequest(xAccountId,
            id,
            hrisDocumentsUploadRequestDto);

        return request;
    }

    public CompletableFuture<HrisUploadEmployeeDocumentResponse> call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        AsyncRequestOperation<HrisUploadEmployeeDocumentRequest, HrisUploadEmployeeDocumentResponse> operation
              = new HrisUploadEmployeeDocument.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        HrisUploadEmployeeDocumentRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
