/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.operations;

import static com.stackone.stackone_client_java.operations.Operations.RequestOperation;

import com.stackone.stackone_client_java.SDKConfiguration;
import com.stackone.stackone_client_java.models.components.MarketingCreatePushTemplateRequestDto;
import com.stackone.stackone_client_java.operations.MarketingCreatePushTemplateOperation;
import com.stackone.stackone_client_java.utils.Options;
import com.stackone.stackone_client_java.utils.RetryConfig;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class MarketingCreatePushTemplateRequestBuilder {

    private String xAccountId;
    private MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public MarketingCreatePushTemplateRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public MarketingCreatePushTemplateRequestBuilder xAccountId(String xAccountId) {
        Utils.checkNotNull(xAccountId, "xAccountId");
        this.xAccountId = xAccountId;
        return this;
    }

    public MarketingCreatePushTemplateRequestBuilder marketingCreatePushTemplateRequestDto(MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto) {
        Utils.checkNotNull(marketingCreatePushTemplateRequestDto, "marketingCreatePushTemplateRequestDto");
        this.marketingCreatePushTemplateRequestDto = marketingCreatePushTemplateRequestDto;
        return this;
    }
                
    public MarketingCreatePushTemplateRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public MarketingCreatePushTemplateRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private MarketingCreatePushTemplateRequest buildRequest() {

        MarketingCreatePushTemplateRequest request = new MarketingCreatePushTemplateRequest(xAccountId,
            marketingCreatePushTemplateRequestDto);

        return request;
    }

    public MarketingCreatePushTemplateResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<MarketingCreatePushTemplateRequest, MarketingCreatePushTemplateResponse> operation
              = new MarketingCreatePushTemplateOperation(sdkConfiguration, options);
        MarketingCreatePushTemplateRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
