/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.stackone.stackone_client_java.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.stackone.stackone_client_java.models.components.MarketingCreatePushTemplateRequestDto;
import com.stackone.stackone_client_java.utils.SpeakeasyMetadata;
import com.stackone.stackone_client_java.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class MarketingCreatePushTemplateRequest {
    /**
     * The account identifier
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-account-id")
    private String xAccountId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto;

    @JsonCreator
    public MarketingCreatePushTemplateRequest(
            String xAccountId,
            MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto) {
        Utils.checkNotNull(xAccountId, "xAccountId");
        Utils.checkNotNull(marketingCreatePushTemplateRequestDto, "marketingCreatePushTemplateRequestDto");
        this.xAccountId = xAccountId;
        this.marketingCreatePushTemplateRequestDto = marketingCreatePushTemplateRequestDto;
    }

    /**
     * The account identifier
     */
    @JsonIgnore
    public String xAccountId() {
        return xAccountId;
    }

    @JsonIgnore
    public MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto() {
        return marketingCreatePushTemplateRequestDto;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The account identifier
     */
    public MarketingCreatePushTemplateRequest withXAccountId(String xAccountId) {
        Utils.checkNotNull(xAccountId, "xAccountId");
        this.xAccountId = xAccountId;
        return this;
    }

    public MarketingCreatePushTemplateRequest withMarketingCreatePushTemplateRequestDto(MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto) {
        Utils.checkNotNull(marketingCreatePushTemplateRequestDto, "marketingCreatePushTemplateRequestDto");
        this.marketingCreatePushTemplateRequestDto = marketingCreatePushTemplateRequestDto;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MarketingCreatePushTemplateRequest other = (MarketingCreatePushTemplateRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xAccountId, other.xAccountId) &&
            Utils.enhancedDeepEquals(this.marketingCreatePushTemplateRequestDto, other.marketingCreatePushTemplateRequestDto);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xAccountId, marketingCreatePushTemplateRequestDto);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MarketingCreatePushTemplateRequest.class,
                "xAccountId", xAccountId,
                "marketingCreatePushTemplateRequestDto", marketingCreatePushTemplateRequestDto);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String xAccountId;

        private MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The account identifier
         */
        public Builder xAccountId(String xAccountId) {
            Utils.checkNotNull(xAccountId, "xAccountId");
            this.xAccountId = xAccountId;
            return this;
        }


        public Builder marketingCreatePushTemplateRequestDto(MarketingCreatePushTemplateRequestDto marketingCreatePushTemplateRequestDto) {
            Utils.checkNotNull(marketingCreatePushTemplateRequestDto, "marketingCreatePushTemplateRequestDto");
            this.marketingCreatePushTemplateRequestDto = marketingCreatePushTemplateRequestDto;
            return this;
        }

        public MarketingCreatePushTemplateRequest build() {

            return new MarketingCreatePushTemplateRequest(
                xAccountId, marketingCreatePushTemplateRequestDto);
        }

    }
}
